// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import 'dart:io' as io;
import 'dart:math' as math;
import 'package:jsontool/jsontool.dart';
import 'package:path/path.dart' as p;
import 'package:characters/characters.dart';
import 'descriptors.dart';
import 'schema.dart';
import 'parser.dart';
import 'utils.dart';

const _vocabValidation =
    'https://json-schema.org/draft/2020-12/vocab/validation';
const _vocabApplicator =
    'https://json-schema.org/draft/2020-12/vocab/applicator';

/// Custom exception tracking the nested path of validation or parse failure.
final class JsonParseException implements FormatException {
  @override
  final String message;

  @override
  final Object? source;

  @override
  final int? offset;

  /// The JSON path segments leading to the failure.
  final List<String> path;

  /// Creates a [JsonParseException] with the failure path.
  JsonParseException(this.message, this.source, this.offset, this.path);

  @override
  String toString() {
    final pathStr = path.isEmpty ? '' : ' at \$.${path.join('.')}';
    return 'JsonParseException$pathStr: $message';
  }
}

/// Helper function to wrap parsing exceptions, adding the path segment.
FormatException wrapException(FormatException e, dynamic pathSegment) {
  final List<String> pathList;
  if (pathSegment is List) {
    pathList = List<String>.from(pathSegment);
  } else {
    pathList = [pathSegment as String];
  }
  if (e is JsonParseException) {
    return JsonParseException(e.message, e.source, e.offset, [
      ...pathList,
      ...e.path,
    ]);
  }
  return JsonParseException(e.message, e.source, e.offset, pathList);
}

/// Base interface for all models generated by json_schema_gen.
abstract interface class JsonModel implements JsonWritable {
  /// Validates the model instance against schema constraints.
  void validate();

  /// Converts the model to a JSON-compatible Dart value (Map, List, primitive, etc.).
  Object? toJsonValue();
}

/// Exception thrown when schema validation fails.
final class JsonValidationException implements Exception {
  /// The validation error message.
  final String message;

  /// The JSON path segments leading to the validation failure.
  final List<String> path;

  /// Creates a [JsonValidationException] with the validation failure path.
  JsonValidationException(this.message, [this.path = const []]);

  @override
  String toString() {
    final pathStr = path.isEmpty ? '' : ' at \$.${path.join('.')}';
    return 'JsonValidationException$pathStr: $message';
  }
}

/// Read any dynamic JSON value from [reader].
dynamic readAny(JsonReader reader) {
  dynamic result;
  final writer = jsonObjectWriter((value) {
    result = value;
  });
  reader.expectAnyValue(writer);
  return result;
}

/// Writes any arbitrary Dart JSON structure to [sink].
void writeAny(JsonSink sink, dynamic value) {
  if (value == null) {
    sink.addNull();
  } else if (value is bool) {
    sink.addBool(value);
  } else if (value is num) {
    sink.addNumber(value);
  } else if (value is String) {
    sink.addString(value);
  } else if (value is List) {
    sink.startArray();
    for (final item in value) {
      writeAny(sink, item);
    }
    sink.endArray();
  } else if (value is Map) {
    sink.startObject();
    value.forEach((key, val) {
      sink.addKey(key.toString());
      writeAny(sink, val);
    });
    sink.endObject();
  } else if (value is JsonWritable) {
    value.writeJson(sink);
  } else {
    throw ArgumentError(
      'Unsupported value type for serialization: ${value.runtimeType}',
    );
  }
}

/// Base class for execution frames used during non-recursive parsing.
///
/// The validator uses a stack-based, non-recursive parser architecture to avoid
/// Dart call-stack overflow when parsing and validating deeply nested JSON structures.
/// Instead of relying on recursive function calls, which consume physical stack space
/// and can lead to StackOverflowErrors, we maintain our own stack of [JsonParseFrame]s
/// on the heap. Each frame manages its own state and progress, and yields control
/// back to the main loop ([_runNonRecursiveWithDescriptor]) when it needs to parse
/// a nested child structure, pushing a new frame onto the stack.
sealed class JsonParseFrame {
  /// The result of parsing this frame.
  dynamic get result;

  /// The current path segment being parsed.
  String? get currentPathSegment;

  /// Resumes execution of this frame with a parsed child [value].
  void resume(dynamic value);

  /// Executes parsing logic for this frame.
  ///
  /// Returns `true` if the frame is complete.
  bool execute(JsonReader reader, List<JsonParseFrame> stack);
}

final class _ObjectFrame extends JsonParseFrame {
  final ObjectDescriptor desc;
  final bool validate;
  final Map<String, dynamic> fields = {};
  bool _initialized = false;
  String? _currentKey;
  dynamic _result;

  _ObjectFrame(this.desc, {this.validate = true});

  @override
  dynamic get result => _result;

  @override
  String? get currentPathSegment => _currentKey;

  @override
  void resume(dynamic value) {
    if (_currentKey != null) {
      fields[_currentKey!] = value;
      _currentKey = null;
    }
  }

  @override
  bool execute(JsonReader reader, List<JsonParseFrame> stack) {
    if (!_initialized) {
      reader.expectObject();
      _initialized = true;
    }
    if (reader.hasNextKey()) {
      final key = reader.nextKey()!;
      final prop = desc.properties[key];
      if (prop != null) {
        _currentKey = key;
        _pushSchemaFrame(reader, stack, prop.schema, (val) {
          fields[key] = val;
          _currentKey = null;
        }, validate: validate);
      } else {
        final matchingPatterns = desc.patternProperties.entries
            .where((e) => e.key.hasMatch(key))
            .toList();
        if (matchingPatterns.isNotEmpty) {
          _currentKey = key;
          _pushSchemaFrame(reader, stack, matchingPatterns.first.value, (val) {
            fields[key] = val;
            _currentKey = null;
          }, validate: validate);
        } else if (desc.additionalProperties != null) {
          _currentKey = key;
          _pushSchemaFrame(reader, stack, desc.additionalProperties!, (val) {
            fields[key] = val;
            _currentKey = null;
          }, validate: validate);
        } else {
          reader.skipAnyValue();
        }
      }
      return false;
    } else {
      for (final req in desc.required) {
        if (!fields.containsKey(req)) {
          throw reader.fail('Missing required property: $req');
        }
      }
      _result = desc.instantiate(fields);
      if (validate && _result is JsonModel) {
        (_result as JsonModel).validate();
      }
      stack.removeLast();
      if (stack.isNotEmpty) {
        stack.last.resume(_result);
      }
      return false;
    }
  }
}

/// Parse frame for array descriptors.
final class ArrayFrame<T> extends JsonParseFrame {
  /// The descriptor for this array.
  final ArrayDescriptor<T> desc;

  /// Whether to validate parsed items.
  final bool validate;

  /// The accumulated list of items.
  final List<T> list = [];

  /// Internal state tracking initialization.
  bool _initialized = false;

  /// Current index being parsed.
  int index = 0;
  dynamic _result;

  /// Creates an [ArrayFrame].
  ArrayFrame(this.desc, {this.validate = true});

  @override
  dynamic get result => list;

  @override
  String? get currentPathSegment => '[$index]';

  @override
  void resume(dynamic value) {
    list.add(value as T);
    index++;
  }

  @override
  bool execute(JsonReader reader, List<JsonParseFrame> stack) {
    if (!_initialized) {
      reader.expectArray();
      _initialized = true;
    }
    if (reader.hasNext()) {
      final itemDesc =
          (desc.prefixItems != null && index < desc.prefixItems!.length)
          ? desc.prefixItems![index]
          : desc.items;
      _pushSchemaFrame(reader, stack, itemDesc, (val) {
        list.add(val as T);
        index++;
      }, validate: validate);
      return false;
    } else {
      _result = list;
      stack.removeLast();
      if (stack.isNotEmpty) {
        stack.last.resume(_result);
      }
      return false;
    }
  }
}

final class _UnionFrame extends JsonParseFrame {
  final UnionDescriptor desc;
  final bool validate;
  dynamic _result;
  UnionOptionDescriptor? _pendingOption;

  _UnionFrame(this.desc, {this.validate = true});

  @override
  dynamic get result => _result;

  @override
  String? get currentPathSegment => null;

  @override
  void resume(dynamic value) {
    if (_pendingOption != null) {
      _result = _pendingOption!.wrap(value);
      _pendingOption = null;
    } else {
      _result = value;
    }
  }

  @override
  bool execute(JsonReader reader, List<JsonParseFrame> stack) {
    if (_result != null) {
      if (validate && _result is JsonModel) {
        (_result as JsonModel).validate();
      }
      stack.removeLast();
      if (stack.isNotEmpty) {
        stack.last.resume(_result);
      }
      return false;
    }

    if (desc.discriminatorProperty != null) {
      final rCopy = reader.copy();
      rCopy.expectObject();
      String? discValue;
      while (rCopy.hasNextKey()) {
        final key = rCopy.nextKey();
        if (key == desc.discriminatorProperty) {
          discValue = rCopy.expectString();
          break;
        } else {
          rCopy.skipAnyValue();
        }
      }
      if (discValue == null) {
        throw reader.fail(
          'Missing discriminator property: ${desc.discriminatorProperty}',
        );
      }
      final option = desc.discriminatorMapping?[discValue];
      if (option == null) {
        throw reader.fail('Unknown discriminator value: $discValue');
      }
      _pendingOption = option;
      _pushSchemaFrame(reader, stack, option.schema, (val) {
        _result = option.wrap(val);
        _pendingOption = null;
      }, validate: validate);
      return false;
    } else {
      FormatException? lastException;
      for (final option in desc.activeOptions) {
        final rCopy = reader.copy();
        try {
          _runNonRecursiveWithDescriptor(rCopy, option.schema, validate: false);
          _pendingOption = option;
          _pushSchemaFrame(reader, stack, option.schema, (val) {
            _result = option.wrap(val);
            _pendingOption = null;
          }, validate: validate);
          return false;
        } on FormatException catch (e) {
          lastException = e;
        }
      }
      throw reader.fail(
        'Failed to parse ${desc.title} union. Last error: ${lastException?.message}',
      );
    }
  }
}

final class _NotFrame extends JsonParseFrame {
  final NotDescriptor desc;
  final bool validate;
  dynamic _result;

  _NotFrame(this.desc, {this.validate = true});

  @override
  dynamic get result => _result;

  @override
  String? get currentPathSegment => null;

  @override
  void resume(dynamic value) {
    // Speculative parsing is done synchronously, so this should not be called.
  }

  @override
  bool execute(JsonReader reader, List<JsonParseFrame> stack) {
    if (validate) {
      final rCopy = reader.copy();
      bool matched = false;
      try {
        _runNonRecursiveWithDescriptor(rCopy, desc.inner, validate: validate);
        matched = true;
      } on JsonValidationException {
        // OK
      } on FormatException {
        // OK
      }

      if (matched) {
        throw JsonValidationException('Value must not match the schema');
      }
    }

    _result = readAny(reader);
    stack.removeLast();
    if (stack.isNotEmpty) {
      stack.last.resume(_result);
    }
    return false;
  }
}

SchemaDescriptor _resolve(SchemaDescriptor schema) {
  var current = schema;
  while (current is RefDescriptor) {
    current = current.target;
  }
  return current;
}

void _pushSchemaFrame(
  JsonReader reader,
  List<JsonParseFrame> stack,
  SchemaDescriptor rawSchema,
  void Function(dynamic value) onComplete, {
  required bool validate,
}) {
  final schema = _resolve(rawSchema);
  if (schema is NullableDescriptor) {
    if (reader.checkNull()) {
      reader.expectNull();
      onComplete(null);
    } else {
      _pushSchemaFrame(
        reader,
        stack,
        schema.inner,
        onComplete,
        validate: validate,
      );
    }
  } else if (schema is PrimitiveDescriptor) {
    onComplete(schema.read(reader));
  } else if (schema is AnythingDescriptor) {
    onComplete(readAny(reader));
  } else if (schema is EnumDescriptor) {
    final val = schema.base.read(reader);
    try {
      onComplete(schema.fromValue(val));
    } catch (e) {
      throw reader.fail('Invalid enum value: $val');
    }
  } else if (schema is ObjectDescriptor) {
    stack.add(_ObjectFrame(schema, validate: validate));
  } else if (schema is ArrayDescriptor) {
    stack.add(schema.createFrame(validate: validate));
  } else if (schema is UnionDescriptor) {
    stack.add(_UnionFrame(schema, validate: validate));
  } else if (schema is NotDescriptor) {
    stack.add(_NotFrame(schema, validate: validate));
  } else if (schema is NeverDescriptor) {
    throw reader.fail('Value is not allowed here');
  }
}

dynamic _runNonRecursiveWithDescriptor(
  JsonReader reader,
  SchemaDescriptor rawRootSchema, {
  bool validate = true,
}) {
  final rootSchema = _resolve(rawRootSchema);
  if (rootSchema is NullableDescriptor) {
    if (reader.checkNull()) {
      reader.expectNull();
      return null;
    }
    return _runNonRecursiveWithDescriptor(
      reader,
      rootSchema.inner,
      validate: validate,
    );
  }
  if (rootSchema is PrimitiveDescriptor) {
    return rootSchema.read(reader);
  } else if (rootSchema is AnythingDescriptor) {
    return readAny(reader);
  } else if (rootSchema is EnumDescriptor) {
    final val = rootSchema.base.read(reader);
    try {
      return rootSchema.fromValue(val);
    } catch (e) {
      throw reader.fail('Invalid enum value: $val');
    }
  }

  final rootFrame = _createFrameForSchema(rootSchema, validate: validate);
  final stack = <JsonParseFrame>[rootFrame];
  try {
    while (stack.isNotEmpty) {
      final current = stack.last;
      final isComplete = current.execute(reader, stack);
      if (isComplete) {
        stack.removeLast();
      }
    }
    return rootFrame.result;
  } on JsonValidationException catch (e) {
    final path = <String>[];
    for (final frame in stack) {
      final segment = frame.currentPathSegment;
      if (segment != null) {
        path.add(segment);
      }
    }
    final propName = path.isNotEmpty ? path.last : null;
    final message = (propName != null && e.message.startsWith('Value '))
        ? e.message.replaceFirst('Value ', 'Property "$propName" ')
        : e.message;
    throw JsonValidationException(message, [...path, ...e.path]);
  } on FormatException catch (e) {
    final path = <String>[];
    for (final frame in stack) {
      final segment = frame.currentPathSegment;
      if (segment != null) {
        path.add(segment);
      }
    }
    throw wrapException(e, path);
  }
}

JsonParseFrame _createFrameForSchema(
  SchemaDescriptor rawSchema, {
  required bool validate,
}) {
  final schema = _resolve(rawSchema);
  if (schema is ObjectDescriptor) {
    return _ObjectFrame(schema, validate: validate);
  } else if (schema is ArrayDescriptor) {
    return schema.createFrame(validate: validate);
  } else if (schema is UnionDescriptor) {
    return _UnionFrame(schema, validate: validate);
  } else if (schema is NotDescriptor) {
    return _NotFrame(schema, validate: validate);
  }
  throw UnsupportedError('Primitive schemas do not require frame creation.');
}

/// Parses JSON from [reader] using the given [schema] descriptor.
///
/// If [validate] is true (default), it will validate the JSON against the
/// schema constraints during parsing.
///
/// Throws [JsonParseException] if the JSON is malformed or cannot be parsed.
/// Throws [JsonValidationException] if the JSON does not conform to the schema.
dynamic parseWithDescriptor(
  JsonReader reader,
  SchemaDescriptor schema, {
  bool validate = true,
}) {
  return _runNonRecursiveWithDescriptor(reader, schema, validate: validate);
}

/// Writes [value] to [sink] using the given [schema] descriptor.
///
/// The [value] must match the structure expected by the [schema] descriptor.
///
/// Throws [ArgumentError] if the value cannot be serialized.
void writeWithDescriptor<T>(
  JsonSink sink,
  T value,
  SchemaDescriptor<T> schema,
) {
  _writeSchemaValue(sink, value, schema);
}

void _writeSchemaValue(
  JsonSink sink,
  Object? value,
  SchemaDescriptor rawSchema,
) {
  final schema = _resolve(rawSchema);
  if (schema is NullableDescriptor) {
    if (value == null) {
      sink.addNull();
    } else {
      _writeSchemaValue(sink, value, schema.inner);
    }
    return;
  }
  if (schema is PrimitiveDescriptor) {
    schema.write(sink, value);
  } else if (schema is AnythingDescriptor) {
    writeAny(sink, value);
  } else if (schema is NotDescriptor) {
    writeAny(sink, value);
  } else if (schema is EnumDescriptor) {
    final backingVal = schema.toValue(value);
    schema.base.write(sink, backingVal);
  } else if (schema is ArrayDescriptor) {
    sink.startArray();
    if (value is List) {
      for (var i = 0; i < value.length; i++) {
        final item = value[i];
        final itemSchema =
            (schema.prefixItems != null && i < schema.prefixItems!.length)
            ? schema.prefixItems![i]
            : schema.items;
        _writeSchemaValue(sink, item, itemSchema);
      }
    }
    sink.endArray();
  } else if (schema is ObjectDescriptor) {
    sink.startObject();
    final fields = schema.getFields(value);
    schema.properties.forEach((key, prop) {
      final val = fields[key];
      if (val != null) {
        sink.addKey(key);
        _writeSchemaValue(sink, val, prop.schema);
      }
    });
    fields.forEach((key, val) {
      if (schema.properties.containsKey(key)) return;
      if (val == null) return;

      final matchingPatterns = schema.patternProperties.entries
          .where((e) => e.key.hasMatch(key))
          .toList();
      if (matchingPatterns.isNotEmpty) {
        sink.addKey(key);
        _writeSchemaValue(sink, val, matchingPatterns.first.value);
      } else if (schema.additionalProperties != null &&
          schema.additionalProperties is! NeverDescriptor) {
        sink.addKey(key);
        _writeSchemaValue(sink, val, schema.additionalProperties!);
      }
    });
    sink.endObject();
  } else if (schema is UnionDescriptor) {
    if (value is JsonWritable) {
      value.writeJson(sink);
    } else {
      var found = false;
      for (final option in schema.activeOptions) {
        if (_descriptorMatches(option.schema, value)) {
          _writeSchemaValue(sink, value, option.schema);
          found = true;
          break;
        }
      }
      if (!found) {
        throw ArgumentError(
          'Value $value does not match any option of union ${schema.title}',
        );
      }
    }
  }
}

bool _descriptorMatches(SchemaDescriptor rawSchema, Object? value) {
  final schema = _resolve(rawSchema);
  if (schema is NullableDescriptor) {
    if (value == null) return true;
    return _descriptorMatches(schema.inner, value);
  }
  if (schema is StringDescriptor) {
    return value is String;
  }
  if (schema is IntDescriptor) {
    return value is int;
  }
  if (schema is NumDescriptor) {
    return value is num;
  }
  if (schema is BoolDescriptor) {
    return value is bool;
  }
  if (schema is NullDescriptor) {
    return value == null;
  }
  if (schema is AnythingDescriptor) {
    return true;
  }
  if (schema is NeverDescriptor) {
    return false;
  }
  if (schema is ArrayDescriptor) {
    return value is List;
  }
  if (schema is ObjectDescriptor) {
    return schema.matches(value);
  }
  if (schema is EnumDescriptor) {
    return schema.values.contains(value);
  }
  if (schema is UnionDescriptor) {
    for (final option in schema.activeOptions) {
      if (_descriptorMatches(option.schema, value)) {
        return true;
      }
    }
    return false;
  }
  return false;
}

/// Validates if a string is a valid hostname according to RFC 1034.
///
/// A hostname must be at most 253 characters long.
/// Labels must be separated by dots and be at most 63 characters long,
/// containing only alphanumeric characters and hyphens, and not starting
/// or ending with a hyphen.
bool isValidHostname(String s) {
  if (s.length > 253) return false;
  final labelRegex = RegExp(
    r'^([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])$',
  );
  final labels = s.split('.');
  for (final label in labels) {
    if (!labelRegex.hasMatch(label)) return false;
  }
  return true;
}

/// Validates if a string is a valid IPv6 address according to RFC 3986.
bool isValidIPv6(String s) {
  final ipv6Regex = RegExp(
    r'^((([0-9A-Fa-f]{1,4}:){7}[0-9A-Fa-f]{1,4})|'
    r'(([0-9A-Fa-f]{1,4}:){1,7}:)|'
    r'(([0-9A-Fa-f]{1,4}:){1,6}:[0-9A-Fa-f]{1,4})|'
    r'(([0-9A-Fa-f]{1,4}:){1,5}:([0-9A-Fa-f]{1,4}:){1,2}[0-9A-Fa-f]{1,4})|'
    r'(([0-9A-Fa-f]{1,4}:){1,4}:([0-9A-Fa-f]{1,4}:){1,3}[0-9A-Fa-f]{1,4})|'
    r'(([0-9A-Fa-f]{1,4}:){1,3}:([0-9A-Fa-f]{1,4}:){1,4}[0-9A-Fa-f]{1,4})|'
    r'(([0-9A-Fa-f]{1,4}:){1,2}:([0-9A-Fa-f]{1,4}:){1,5}[0-9A-Fa-f]{1,4})|'
    r'([0-9A-Fa-f]{1,4}::([0-9A-Fa-f]{1,4}:){1,6}[0-9A-Fa-f]{1,4})|'
    r'(:(:([0-9A-Fa-f]{1,4}:){0,7}[0-9A-Fa-f]{1,4}|:))|'
    r'(fe80:(:[0-9A-Fa-f]{1,4}){0,4}%[0-9a-zA-Z]{1,})|'
    r'(::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))|'
    r'(([0-9A-Fa-f]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])))$',
  );
  return ipv6Regex.hasMatch(s);
}

/// Validates if a string is a valid time string (HH:MM:SS.sss) according to RFC 3339.
bool isValidTime(String s) {
  final timeRegex = RegExp(
    r'^([01][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?([zZ]|[+-](?:[01][0-9]|2[0-3]):[0-5][0-9])$',
  );
  return timeRegex.hasMatch(s);
}

/// Validates if a string is a valid URI reference according to RFC 3986.
bool isValidUriReference(String s) {
  if (Uri.tryParse(s) == null) return false;
  final allowedChars = RegExp(r"^[A-Za-z0-9\-._~:/?#\[\]@!$&'()*+,;=%]*$");
  if (!allowedChars.hasMatch(s)) return false;

  final percentCheck = RegExp(r'%[0-9a-fA-F]{2}');
  var index = 0;
  while ((index = s.indexOf('%', index)) != -1) {
    if (index + 2 >= s.length) return false;
    final part = s.substring(index, index + 3);
    if (!percentCheck.hasMatch(part)) return false;
    index += 3;
  }
  return true;
}

/// Validates if a string is a valid absolute URI according to RFC 3986.
bool isValidUri(String s) {
  if (!isValidUriReference(s)) return false;
  final parsed = Uri.tryParse(s);
  return parsed != null && parsed.hasScheme;
}

/// Extension on [Schema] to support runtime validation.
///
/// {@example /example/lib/manual_validation.dart}
extension SchemaValidationExtension on Schema {
  /// Validates [value] against this schema.
  ///
  /// Throws [JsonValidationException] if validation fails.
  void validate(dynamic value, {bool validateFormats = false}) {
    _Validator(
      validateFormats: validateFormats,
      dynamicAnchors: dynamicAnchors ?? const {},
    ).validate(value, this, _ValidationPath.empty);
  }
}

/// Creates a validator function for the given JSON [schema].
///
/// The returned function takes a decoded JSON value and validates it.
/// It throws [JsonValidationException] if validation fails.
Future<void Function(dynamic)> createValidator(
  Map<String, dynamic> schema, {
  Future<List<int>> Function(Uri uri)? uriResolver,
  bool disallowExternalRefs = true,
  bool flatten = false,
  bool validateFormats = false,
}) async {
  final parser = SchemaParser(
    schema,
    uriResolver: uriResolver,
    disallowExternalRefs: disallowExternalRefs,
    flatten: flatten,
  );
  final parsedSchema = await parser.parse();
  return (dynamic value) =>
      parsedSchema.validate(value, validateFormats: validateFormats);
}

abstract class _ValidationPath {
  static const _ValidationPath empty = _EmptyPath();
  _ValidationPath append(Object segment);
  List<String> toList();
}

class _EmptyPath implements _ValidationPath {
  const _EmptyPath();
  @override
  _ValidationPath append(Object segment) => _SegmentPath(this, segment);
  @override
  List<String> toList() => const [];
}

class _SegmentPath implements _ValidationPath {
  final _ValidationPath parent;
  final Object segment;
  _SegmentPath(this.parent, this.segment);

  @override
  _ValidationPath append(Object segment) => _SegmentPath(this, segment);

  @override
  List<String> toList() {
    final result = <String>[];
    _build(result);
    return result;
  }

  void _build(List<String> list) {
    if (parent is _SegmentPath) {
      (parent as _SegmentPath)._build(list);
    }
    list.add(segment.toString());
  }
}

class _EvaluationTracker {
  final Set<String> evaluatedProperties = {};
  final Set<int> evaluatedItems = {};

  _EvaluationTracker();

  void merge(_EvaluationTracker other) {
    evaluatedProperties.addAll(other.evaluatedProperties);
    evaluatedItems.addAll(other.evaluatedItems);
  }
}

class _Validator {
  final bool validateFormats;
  final Map<String, Schema> dynamicAnchors;
  final List<String> dynamicScope = []; // Track resource URIs (IDs)

  _Validator({this.validateFormats = false, this.dynamicAnchors = const {}});

  _EvaluationTracker validate(
    dynamic value,
    Schema schema,
    _ValidationPath path,
  ) {
    final tracker = _EvaluationTracker();

    if (schema.isNever) {
      throw JsonValidationException(
        'Value matches "never" schema',
        path.toList(),
      );
    }

    if (schema.isAnything) {
      return tracker;
    }

    final vocabs = schema.vocabularies;
    final hasValidation = vocabs == null || vocabs.contains(_vocabValidation);
    final hasApplicator = vocabs == null || vocabs.contains(_vocabApplicator);

    final resourceUri = schema.resourceUri;
    final pushed =
        resourceUri != null &&
        (dynamicScope.isEmpty || dynamicScope.last != resourceUri);
    if (pushed) {
      dynamicScope.add(resourceUri);
    }

    try {
      // Check 'not'
      if (hasApplicator && schema.not != null) {
        bool matches = true;
        try {
          validate(value, schema.not!, path);
        } on JsonValidationException {
          matches = false;
        }
        if (matches) {
          throw JsonValidationException(
            'Value must not match the schema',
            path.toList(),
          );
        }
      }

      // Resolve ref / dynamicRef
      if (schema.ref != null || schema.dynamicRef != null) {
        Schema? target;
        if (schema.dynamicRef != null) {
          // Draft 2020-12 dynamic reference resolution ($dynamicRef).
          // A dynamic reference behaves like a normal reference unless the target schema
          // has a matching `$dynamicAnchor`. If it does, we look up the dynamic scoping stack
          // (represented by [dynamicScope], which tracks the URIs of schemas we have entered).
          // We traverse the stack from oldest to newest (outermost to innermost) to find the first
          // schema resource that defines a dynamic anchor with the same name.
          // This allows subschemas to be overridden by outer schemas that redefine the anchor,
          // supporting extensibility patterns similar to inheritance.
          final lexicalTarget = schema.realSchema;
          final refUri = Uri.parse(schema.dynamicRef!);
          final anchor = refUri.fragment;
          if (anchor.isNotEmpty && lexicalTarget.dynamicAnchor == anchor) {
            for (final uri in dynamicScope) {
              final targetUri = Uri.parse(
                uri,
              ).replace(fragment: anchor).toString();
              if (dynamicAnchors.containsKey(targetUri)) {
                target = dynamicAnchors[targetUri];
                break;
              }
            }
          }
          target ??= lexicalTarget;
        } else {
          target = schema.resolvedRef!;
        }

        final refTracker = validate(value, target, path);
        tracker.merge(refTracker);
      }

      if (hasValidation) {
        // Type validation
        if (schema.type != null) {
          _validateType(value, schema.type!, schema.hasExplicitType, path);
        }

        // Enum validation
        if (schema.enumValues != null) {
          if (!schema.enumValues!.any((v) => deepEquals(v, value))) {
            throw JsonValidationException(
              'Value must be one of: ${schema.enumValues}',
              path.toList(),
            );
          }
        }

        // Const validation
        if (schema.constValue != null) {
          if (!deepEquals(schema.constValue, value)) {
            throw JsonValidationException(
              'Value must be const: ${schema.constValue}',
              path.toList(),
            );
          }
        }
      }

      // Object validation
      if (value is Map) {
        final objTracker = _validateObject(value, schema, path, this);
        tracker.merge(objTracker);
      }

      // Array validation
      if (value is List) {
        final arrTracker = _validateArray(value, schema, path, this);
        tracker.merge(arrTracker);
      }

      // String validation
      if (value is String) {
        _validateString(value, schema, path, validateFormats: validateFormats);
      }

      // Number validation
      if (value is num) {
        _validateNumber(value, schema, path);
      }

      // Combinators
      if (hasApplicator) {
        if (schema.discriminator != null) {
          if (value is! Map) {
            throw JsonValidationException(
              'Value must be an object for discriminator validation',
              path.toList(),
            );
          }
          final propName = schema.discriminator!.propertyName;
          final discValue = value[propName];
          if (discValue == null) {
            throw JsonValidationException(
              'Missing discriminator property: $propName',
              path.toList(),
            );
          }
          if (discValue is! String) {
            throw JsonValidationException(
              'Discriminator property $propName must be a string',
              path.toList(),
            );
          }
          final targetSchema = schema.discriminator!.mapping?[discValue];
          if (targetSchema == null) {
            throw JsonValidationException(
              'Unknown discriminator value: $discValue',
              path.toList(),
            );
          }
          final subTracker = validate(value, targetSchema, path);
          tracker.merge(subTracker);
          return tracker;
        }

        if (schema.allOf != null) {
          for (final sub in schema.allOf!) {
            final subTracker = validate(value, sub, path);
            tracker.merge(subTracker);
          }
        }

        if (schema.anyOf != null) {
          bool anyValid = false;
          final mergedTracker = _EvaluationTracker();
          List<JsonValidationException> errors = [];
          for (final sub in schema.anyOf!) {
            try {
              final subTracker = validate(value, sub, path);
              mergedTracker.merge(subTracker);
              anyValid = true;
            } on JsonValidationException catch (e) {
              errors.add(e);
            }
          }
          if (!anyValid) {
            throw JsonValidationException(
              'Value does not match any of the subschemas. Errors: $errors',
              path.toList(),
            );
          }
          tracker.merge(mergedTracker);
        }

        if (schema.oneOf != null) {
          int validCount = 0;
          _EvaluationTracker? singleTracker;
          List<JsonValidationException> errors = [];
          for (final sub in schema.oneOf!) {
            try {
              final subTracker = validate(value, sub, path);
              singleTracker = subTracker;
              validCount++;
            } on JsonValidationException catch (e) {
              errors.add(e);
            }
          }
          if (validCount != 1) {
            throw JsonValidationException(
              'Value must match exactly one subschema (matched $validCount). Errors: $errors',
              path.toList(),
            );
          }
          tracker.merge(singleTracker!);
        }

        if (schema.ifSchema != null) {
          bool ifSucceeded = false;
          _EvaluationTracker? ifTracker;
          try {
            ifTracker = validate(value, schema.ifSchema!, path);
            ifSucceeded = true;
          } on JsonValidationException catch (_) {
            // failed
          }

          if (ifSucceeded) {
            tracker.merge(ifTracker!);
            if (schema.thenSchema != null) {
              final thenTracker = validate(value, schema.thenSchema!, path);
              tracker.merge(thenTracker);
            }
          } else {
            if (schema.elseSchema != null) {
              final elseTracker = validate(value, schema.elseSchema!, path);
              tracker.merge(elseTracker);
            }
          }
        }

        // Unevaluated validation
        if (value is Map && schema.unevaluatedProperties != null) {
          value.forEach((key, val) {
            if (!tracker.evaluatedProperties.contains(key)) {
              final subTracker = validate(
                val,
                schema.unevaluatedProperties!,
                path.append(key as Object),
              );
              tracker.merge(subTracker);
              tracker.evaluatedProperties.add(key.toString());
            }
          });
        }

        if (value is List && schema.unevaluatedItems != null) {
          value.asMap().forEach((index, val) {
            if (!tracker.evaluatedItems.contains(index)) {
              final subTracker = validate(
                val,
                schema.unevaluatedItems!,
                path.append(index),
              );
              tracker.merge(subTracker);
              tracker.evaluatedItems.add(index);
            }
          });
        }
      }
    } finally {
      if (pushed) {
        dynamicScope.removeLast();
      }
    }

    return tracker;
  }
}

void _validateType(
  dynamic value,
  List<String> allowedTypes,
  bool hasExplicitType,
  _ValidationPath path,
) {
  bool matches = false;
  for (final type in allowedTypes) {
    if (type == 'null' && value == null) matches = true;
    if (type == 'boolean' && value is bool) matches = true;
    if (type == 'string' && value is String) matches = true;
    if (type == 'number' && value is num) matches = true;
    if (type == 'integer' && value is num) {
      if (value is int || value == value.toInt()) {
        matches = true;
      }
    }
    if (type == 'object' && value is Map) matches = true;
    if (type == 'array' && value is List) matches = true;
  }
  if (!matches) {
    if (hasExplicitType) {
      throw JsonValidationException(
        'Value must be one of type: $allowedTypes',
        path.toList(),
      );
    }
  }
}

void _validateNumber(dynamic value, Schema schema, _ValidationPath path) {
  if (schema.vocabularies != null &&
      !schema.vocabularies!.contains(_vocabValidation)) {
    return;
  }
  if (value is! num) {
    if (schema.hasExplicitType) {
      throw JsonValidationException('Value must be a number', path.toList());
    }
    return;
  }
  if (schema.isInteger) {
    if (value is! int && value != value.toInt()) {
      throw JsonValidationException('Value must be an integer', path.toList());
    }
  }

  final val = value;
  if (schema.minimum != null && val < schema.minimum!) {
    throw JsonValidationException(
      'Value must be >= ${schema.minimum}',
      path.toList(),
    );
  }
  if (schema.maximum != null && val > schema.maximum!) {
    throw JsonValidationException(
      'Value must be <= ${schema.maximum}',
      path.toList(),
    );
  }
  if (schema.exclusiveMinimum != null && val <= schema.exclusiveMinimum!) {
    throw JsonValidationException(
      'Value must be > ${schema.exclusiveMinimum}',
      path.toList(),
    );
  }
  if (schema.exclusiveMaximum != null && val >= schema.exclusiveMaximum!) {
    throw JsonValidationException(
      'Value must be < ${schema.exclusiveMaximum}',
      path.toList(),
    );
  }
  if (schema.multipleOf != null) {
    final valInt = parseInt(val);
    final mInt = parseInt(schema.multipleOf);
    if (valInt != null && mInt != null) {
      if (valInt % mInt != 0) {
        throw JsonValidationException(
          'Value must be a multiple of ${schema.multipleOf}',
          path.toList(),
        );
      }
    } else {
      final div = val / schema.multipleOf!;
      final rounded = div.round();
      final absError = (div - rounded).abs();
      final relError = absError / math.max(div.abs(), 1.0);
      if (relError > 1e-14) {
        throw JsonValidationException(
          'Value must be a multiple of ${schema.multipleOf}',
          path.toList(),
        );
      }
    }
  }
}

void _validateString(
  dynamic value,
  Schema schema,
  _ValidationPath path, {
  bool validateFormats = false,
}) {
  if (schema.vocabularies != null &&
      !schema.vocabularies!.contains(_vocabValidation)) {
    return;
  }
  if (value is! String) {
    if (schema.hasExplicitType) {
      throw JsonValidationException('Value must be a string', path.toList());
    }
    return;
  }
  if (schema.minLength != null && value.characters.length < schema.minLength!) {
    throw JsonValidationException(
      'Value length must be >= ${schema.minLength}',
      path.toList(),
    );
  }
  if (schema.maxLength != null && value.characters.length > schema.maxLength!) {
    throw JsonValidationException(
      'Value length must be <= ${schema.maxLength}',
      path.toList(),
    );
  }
  if (schema.pattern != null) {
    final regExp = RegExp(schema.pattern!, unicode: true);
    if (!regExp.hasMatch(value)) {
      throw JsonValidationException(
        'Value must match pattern: ${schema.pattern}',
        path.toList(),
      );
    }
  }
  if (schema.format != null && validateFormats) {
    switch (schema.format) {
      case 'date-time':
        final r = RegExp(
          r'^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})?$',
        );
        if (!r.hasMatch(value)) {
          throw JsonValidationException(
            'Value must be a valid date-time string',
            path.toList(),
          );
        }
        break;
      case 'email':
        final r = RegExp(r'^[^@]+@[^@]+\.[^@]+$');
        if (!r.hasMatch(value)) {
          throw JsonValidationException(
            'Value must be a valid email address',
            path.toList(),
          );
        }
        break;
      case 'hostname':
        final r = RegExp(
          r'^([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])'
          r'(\.([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9]))*$',
        );
        if (!r.hasMatch(value) || value.length > 255) {
          throw JsonValidationException(
            'Value must be a valid hostname',
            path.toList(),
          );
        }
        break;
      case 'ipv4':
        final r = RegExp(
          r'^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}'
          r'(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$',
        );
        if (!r.hasMatch(value)) {
          throw JsonValidationException(
            'Value must be a valid IPv4 address',
            path.toList(),
          );
        }
        break;
      case 'ipv6':
        final r = RegExp(r'^([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}$');
        final r2 = RegExp(
          r'^((?:[0-9A-Fa-f]{1,4}(?::[0-9A-Fa-f]{1,4})*)?)::'
          r'((?:[0-9A-Fa-f]{1,4}(?::[0-9A-Fa-f]{1,4})*)?)$',
        );
        if (!r.hasMatch(value) && !r2.hasMatch(value)) {
          throw JsonValidationException(
            'Value must be a valid IPv6 address',
            path.toList(),
          );
        }
        break;
      case 'uri':
        try {
          final uri = Uri.parse(value);
          if (!uri.hasScheme) {
            throw JsonValidationException(
              'Value must be a valid URI (missing scheme)',
              path.toList(),
            );
          }
        } catch (e) {
          throw JsonValidationException(
            'Value must be a valid URI',
            path.toList(),
          );
        }
        break;
      case 'uri-reference':
        if (!isValidUriReference(value)) {
          throw JsonValidationException(
            'Value must be a valid URI reference',
            path.toList(),
          );
        }
        break;
      case 'uuid':
        final r = RegExp(
          r'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-'
          r'[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
        );
        if (!r.hasMatch(value)) {
          throw JsonValidationException(
            'Value must be a valid UUID',
            path.toList(),
          );
        }
        break;
      case 'regex':
        try {
          RegExp(value);
        } catch (e) {
          throw JsonValidationException(
            'Value must be a valid regular expression',
            path.toList(),
          );
        }
        break;
      case 'date':
        final r = RegExp(r'^\d{4}-\d{2}-\d{2}$');
        if (!r.hasMatch(value)) {
          throw JsonValidationException(
            'Value must be a valid date string',
            path.toList(),
          );
        }
        break;
      case 'time':
        if (!isValidTime(value)) {
          throw JsonValidationException(
            'Value must be a valid time string',
            path.toList(),
          );
        }
        break;
    }
  }
}

_EvaluationTracker _validateArray(
  dynamic value,
  Schema schema,
  _ValidationPath path,
  _Validator validator,
) {
  final tracker = _EvaluationTracker();
  if (value is! List) return tracker;
  final list = value;

  final vocabs = schema.vocabularies;
  final hasValidation = vocabs == null || vocabs.contains(_vocabValidation);
  final hasApplicator = vocabs == null || vocabs.contains(_vocabApplicator);

  if (hasValidation) {
    if (schema.minItems != null && list.length < schema.minItems!) {
      throw JsonValidationException(
        'Value must have >= ${schema.minItems} items',
        path.toList(),
      );
    }
    if (schema.maxItems != null && list.length > schema.maxItems!) {
      throw JsonValidationException(
        'Value must have <= ${schema.maxItems} items',
        path.toList(),
      );
    }

    if (schema.uniqueItems == true) {
      for (var i = 0; i < list.length; i++) {
        for (var j = i + 1; j < list.length; j++) {
          if (deepEquals(list[i], list[j])) {
            throw JsonValidationException(
              'Value must have unique items, but items at indices $i and $j are equal',
              path.toList(),
            );
          }
        }
      }
    }
  }

  var prefixItemsCount = 0;
  if (hasApplicator) {
    if (schema.prefixItems != null) {
      prefixItemsCount = schema.prefixItems!.length;
      for (var i = 0; i < math.min(list.length, prefixItemsCount); i++) {
        validator.validate(list[i], schema.prefixItems![i], path.append(i));
        tracker.evaluatedItems.add(i);
      }
    }

    if (schema.items != null) {
      for (var i = prefixItemsCount; i < list.length; i++) {
        validator.validate(list[i], schema.items!, path.append(i));
        tracker.evaluatedItems.add(i);
      }
    }

    if (schema.contains != null) {
      var containsCount = 0;
      for (var i = 0; i < list.length; i++) {
        try {
          validator.validate(list[i], schema.contains!, path.append(i));
          containsCount++;
          tracker.evaluatedItems.add(i);
        } on JsonValidationException {
          // Ignore
        }
      }

      final minContains = hasValidation ? (schema.minContains ?? 1) : 1;
      if (containsCount < minContains) {
        throw JsonValidationException(
          'Value must contain at least $minContains items matching contains schema (matched $containsCount)',
          path.toList(),
        );
      }
      if (hasValidation &&
          schema.maxContains != null &&
          containsCount > schema.maxContains!) {
        throw JsonValidationException(
          'Value must contain at most ${schema.maxContains} items matching contains schema',
          path.toList(),
        );
      }
    }
  }

  return tracker;
}

_EvaluationTracker _validateObject(
  dynamic value,
  Schema schema,
  _ValidationPath path,
  _Validator validator,
) {
  final tracker = _EvaluationTracker();
  if (value is! Map) return tracker;
  final map = value;

  final vocabs = schema.vocabularies;
  final hasValidation = vocabs == null || vocabs.contains(_vocabValidation);
  final hasApplicator = vocabs == null || vocabs.contains(_vocabApplicator);

  if (hasValidation) {
    if (schema.required != null) {
      for (final req in schema.required!) {
        if (!map.containsKey(req)) {
          throw JsonValidationException(
            'Missing required property: $req',
            path.append(req).toList(),
          );
        }
      }
    }

    if (schema.minProperties != null && map.length < schema.minProperties!) {
      throw JsonValidationException(
        'Object must have >= ${schema.minProperties} properties',
        path.toList(),
      );
    }
    if (schema.maxProperties != null && map.length > schema.maxProperties!) {
      throw JsonValidationException(
        'Object must have <= ${schema.maxProperties} properties',
        path.toList(),
      );
    }
  }

  map.forEach((key, val) {
    if (key is! String) {
      throw JsonValidationException(
        'Object keys must be strings',
        path.toList(),
      );
    }

    if (hasApplicator && schema.propertyNames != null) {
      validator.validate(key, schema.propertyNames!, path.append(key));
    }

    var evaluated = false;

    if (hasApplicator) {
      if (schema.properties != null) {
        final propSchema = schema.properties![key];
        if (propSchema != null) {
          validator.validate(val, propSchema, path.append(key));
          tracker.evaluatedProperties.add(key);
          evaluated = true;
        }
      }

      if (schema.patternProperties != null) {
        schema.patternProperties!.forEach((pattern, patternSchema) {
          if (pattern.hasMatch(key)) {
            validator.validate(val, patternSchema, path.append(key));
            tracker.evaluatedProperties.add(key);
            evaluated = true;
          }
        });
      }

      if (!evaluated) {
        final addProps = schema.additionalProperties;
        if (addProps != null) {
          validator.validate(val, addProps, path.append(key));
          tracker.evaluatedProperties.add(key);
        }
      }
    }
  });

  if (hasValidation) {
    schema.dependentRequired?.forEach((key, deps) {
      if (map.containsKey(key)) {
        for (final dep in deps) {
          if (!map.containsKey(dep)) {
            throw JsonValidationException(
              'Property "$dep" is required because "$key" is present',
              path.append(dep).toList(),
            );
          }
        }
      }
    });
  }

  if (hasApplicator) {
    schema.dependentSchemas?.forEach((key, depSchema) {
      if (map.containsKey(key)) {
        final depTracker = validator.validate(value, depSchema, path);
        tracker.merge(depTracker);
      }
    });
  }

  return tracker;
}

/// A resolver that loads schemas from the local file system.
Future<List<int>> ioFileResolver(
  Uri uri, {
  io.Directory? rootDirectory,
  bool restrictToRoot = true,
}) async {
  if (uri.scheme != 'file' && uri.scheme != '') {
    throw ArgumentError(
      'Unsupported scheme: ${uri.scheme}. Only file URIs are supported.',
    );
  }
  final file = io.File.fromUri(uri);
  if (restrictToRoot) {
    final root = rootDirectory ?? io.Directory.current;
    final rootPath = p.canonicalize(root.path);
    final filePath = p.canonicalize(file.path);

    if (!p.isWithin(rootPath, filePath) && !p.equals(rootPath, filePath)) {
      throw ArgumentError(
        'Access denied: $uri is outside of restricted root $rootPath',
      );
    }
  }
  return file.readAsBytes();
}
