// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import 'dart:math' as math;
import 'package:jsontool/jsontool.dart';
import 'descriptors.dart';
import 'schema.dart';
import 'parser.dart';
import 'utils.dart';

const _vocabValidation =
    'https://json-schema.org/draft/2020-12/vocab/validation';
const _vocabApplicator =
    'https://json-schema.org/draft/2020-12/vocab/applicator';

/// Custom exception tracking the nested path of validation or parse failure.
final class JsonParseException implements FormatException {
  @override
  final String message;

  @override
  final Object? source;

  @override
  final int? offset;

  /// The JSON path segments leading to the failure.
  final List<String> path;

  /// Creates a [JsonParseException] with the failure path.
  JsonParseException(this.message, this.source, this.offset, this.path);

  @override
  String toString() {
    final pathStr = path.isEmpty ? '' : ' at \$.${path.join('.')}';
    return 'JsonParseException$pathStr: $message';
  }
}

/// Helper function to wrap parsing exceptions, adding the path segment.
FormatException wrapException(FormatException e, dynamic pathSegment) {
  final List<String> pathList;
  if (pathSegment is List) {
    pathList = List<String>.from(pathSegment);
  } else {
    pathList = [pathSegment as String];
  }
  if (e is JsonParseException) {
    return JsonParseException(e.message, e.source, e.offset, [
      ...pathList,
      ...e.path,
    ]);
  }
  return JsonParseException(e.message, e.source, e.offset, pathList);
}

/// Base interface for all models generated by json_schema_gen.
abstract interface class JsonModel implements JsonWritable {
  /// Validates the model instance against schema constraints and returns all errors.
  List<ValidationError> collectErrors();

  /// Validates the model instance against schema constraints.
  /// Throws [JsonValidationException] containing all errors if validation fails.
  void validate();

  /// Converts the model to a JSON-compatible Dart value (Map, List, primitive, etc.).
  Object? toJsonValue();
}

/// Represents a validation error encountered during schema validation.
class ValidationError {
  /// The validation error message.
  final String message;

  /// The JSON path segments leading to the validation failure.
  final List<String> path;

  /// The schema keyword that failed (e.g. 'required', 'type', 'minimum', 'anyOf').
  final String? keyword;

  /// The schema definition under which this error occurred, if available.
  final Schema? schema;

  /// The rejected value that caused the validation failure.
  final dynamic value;

  /// Nested errors from subschemas, e.g. for 'anyOf' or 'oneOf' failures.
  final List<ValidationError> nestedErrors;

  /// Creates a [ValidationError].
  const ValidationError({
    required this.message,
    this.path = const [],
    this.keyword,
    this.schema,
    this.value,
    this.nestedErrors = const [],
  });

  /// The JSON Pointer (RFC 6901) representation of [path], e.g. "/items/0/name".
  String get instancePath {
    if (path.isEmpty) return '';
    return '/${path.map((s) => s.replaceAll('~', '~0').replaceAll('/', '~1')).join('/')}';
  }

  /// The dot-separated JSONPath representation of [path], e.g. "$.items.0.name".
  String get jsonPath {
    if (path.isEmpty) return r'$';
    return r'$.' + path.join('.');
  }

  @override
  String toString() {
    final loc = jsonPath;
    final kw = keyword != null ? ' ($keyword)' : '';
    return 'ValidationError at $loc$kw: $message';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ValidationError &&
          runtimeType == other.runtimeType &&
          message == other.message &&
          keyword == other.keyword &&
          _listEquals(path, other.path) &&
          _listEquals(nestedErrors, other.nestedErrors);

  @override
  int get hashCode => Object.hash(
    message,
    keyword,
    Object.hashAll(path),
    Object.hashAll(nestedErrors),
  );

  static bool _listEquals(List<Object?> a, List<Object?> b) {
    if (identical(a, b)) return true;
    if (a.length != b.length) return false;
    for (var i = 0; i < a.length; i++) {
      if (a[i] != b[i]) return false;
    }
    return true;
  }
}

/// Exception thrown when schema validation fails.
final class JsonValidationException implements Exception {
  /// All validation errors that occurred.
  final List<ValidationError> errors;

  /// Creates a [JsonValidationException] from a list of accumulated errors.
  JsonValidationException(Iterable<ValidationError> errors)
    : errors = List.unmodifiable(errors) {
    if (this.errors.isEmpty) {
      throw ArgumentError.value(
        errors,
        'errors',
        'Cannot create JsonValidationException with empty errors',
      );
    }
  }

  /// Convenience factory for a single error.
  factory JsonValidationException.single(
    String message, {
    List<String> path = const [],
    String? keyword,
    Schema? schema,
    dynamic value,
  }) => JsonValidationException([
    ValidationError(
      message: message,
      path: path,
      keyword: keyword,
      schema: schema,
      value: value,
    ),
  ]);

  /// Creates a [JsonValidationException] from a non-empty list of accumulated errors.
  factory JsonValidationException.fromErrors(
    Iterable<ValidationError> errors,
  ) => JsonValidationException(errors);

  /// The first error in [errors].
  ValidationError get primaryError => errors.first;

  /// The JSON path segments of the primary validation failure.
  List<String> get path => primaryError.path;

  /// The validation error message, or an aggregate summary if multiple errors occurred.
  String get message => errors.length == 1
      ? primaryError.message
      : '${errors.length} validation errors: ${errors.map((e) => e.message).join('; ')}';

  @override
  String toString() {
    if (errors.length <= 1) {
      final pathStr = path.isEmpty ? '' : ' at \$.${path.join('.')}';
      return 'JsonValidationException$pathStr: $message';
    }
    final buffer = StringBuffer(
      'JsonValidationException: ${errors.length} validation error(s):\n',
    );
    for (var i = 0; i < errors.length; i++) {
      buffer.writeln('  ${i + 1}. ${errors[i]}');
    }
    return buffer.toString().trimRight();
  }
}

/// Read any dynamic JSON value from [reader].
dynamic readAny(JsonReader reader) {
  dynamic result;
  final writer = jsonObjectWriter((value) {
    result = value;
  });
  reader.expectAnyValue(writer);
  return result;
}

/// Writes any arbitrary Dart JSON structure to [sink].
void writeAny(JsonSink sink, dynamic value) {
  if (value == null) {
    sink.addNull();
  } else if (value is bool) {
    sink.addBool(value);
  } else if (value is num) {
    sink.addNumber(value);
  } else if (value is String) {
    sink.addString(value);
  } else if (value is List) {
    sink.startArray();
    for (final item in value) {
      writeAny(sink, item);
    }
    sink.endArray();
  } else if (value is Map) {
    sink.startObject();
    value.forEach((key, val) {
      sink.addKey(key.toString());
      writeAny(sink, val);
    });
    sink.endObject();
  } else if (value is JsonWritable) {
    value.writeJson(sink);
  } else {
    throw ArgumentError(
      'Unsupported value type for serialization: ${value.runtimeType}',
    );
  }
}

/// Base class for execution frames used during non-recursive parsing.
///
/// The validator uses a stack-based, non-recursive parser architecture to avoid
/// Dart call-stack overflow when parsing and validating deeply nested JSON structures.
/// Instead of relying on recursive function calls, which consume physical stack space
/// and can lead to StackOverflowErrors, we maintain our own stack of [JsonParseFrame]s
/// on the heap. Each frame manages its own state and progress, and yields control
/// back to the main loop ([_runNonRecursiveWithDescriptor]) when it needs to parse
/// a nested child structure, pushing a new frame onto the stack.
sealed class JsonParseFrame {
  /// The result of parsing this frame.
  dynamic get result;

  /// The current path segment being parsed.
  String? get currentPathSegment;

  /// Resumes execution of this frame with a parsed child [value].
  void resume(dynamic value);

  /// Executes parsing logic for this frame.
  ///
  /// Returns `true` if the frame is complete.
  bool execute(JsonReader reader, List<JsonParseFrame> stack);
}

final class _ObjectFrame extends JsonParseFrame {
  final ObjectDescriptor desc;
  final bool validate;
  final Map<String, dynamic> fields = {};
  bool _initialized = false;
  String? _currentKey;
  dynamic _result;

  _ObjectFrame(this.desc, {this.validate = true});

  @override
  dynamic get result => _result;

  @override
  String? get currentPathSegment => _currentKey;

  @override
  void resume(dynamic value) {
    if (_currentKey != null) {
      fields[_currentKey!] = value;
      _currentKey = null;
    }
  }

  @override
  bool execute(JsonReader reader, List<JsonParseFrame> stack) {
    if (!_initialized) {
      reader.expectObject();
      _initialized = true;
    }
    if (reader.hasNextKey()) {
      final key = reader.nextKey()!;
      final prop = desc.properties[key];
      if (prop != null) {
        _currentKey = key;
        _pushSchemaFrame(reader, stack, prop.schema, (val) {
          fields[key] = val;
          _currentKey = null;
        }, validate: validate);
      } else {
        final matchingPatterns = desc.patternProperties.entries
            .where((e) => e.key.hasMatch(key))
            .toList();
        if (matchingPatterns.isNotEmpty) {
          _currentKey = key;
          _pushSchemaFrame(reader, stack, matchingPatterns.first.value, (val) {
            fields[key] = val;
            _currentKey = null;
          }, validate: validate);
        } else if (desc.additionalProperties != null) {
          _currentKey = key;
          _pushSchemaFrame(reader, stack, desc.additionalProperties!, (val) {
            fields[key] = val;
            _currentKey = null;
          }, validate: validate);
        } else {
          reader.skipAnyValue();
        }
      }
      return false;
    } else {
      for (final req in desc.required) {
        if (!fields.containsKey(req)) {
          throw reader.fail('Missing required property: $req');
        }
      }
      _result = desc.instantiate(fields);
      if (validate && _result is JsonModel) {
        (_result as JsonModel).validate();
      }
      stack.removeLast();
      if (stack.isNotEmpty) {
        stack.last.resume(_result);
      }
      return false;
    }
  }
}

/// Parse frame for array descriptors.
final class ArrayFrame<T> extends JsonParseFrame {
  /// The descriptor for this array.
  final ArrayDescriptor<T> desc;

  /// Whether to validate parsed items.
  final bool validate;

  /// The accumulated list of items.
  final List<T> list = [];

  /// Internal state tracking initialization.
  bool _initialized = false;

  /// Current index being parsed.
  int index = 0;
  dynamic _result;

  /// Creates an [ArrayFrame].
  ArrayFrame(this.desc, {this.validate = true});

  @override
  dynamic get result => list;

  @override
  String? get currentPathSegment => '[$index]';

  @override
  void resume(dynamic value) {
    list.add(value as T);
    index++;
  }

  @override
  bool execute(JsonReader reader, List<JsonParseFrame> stack) {
    if (!_initialized) {
      reader.expectArray();
      _initialized = true;
    }
    if (reader.hasNext()) {
      final itemDesc =
          (desc.prefixItems != null && index < desc.prefixItems!.length)
          ? desc.prefixItems![index]
          : desc.items;
      _pushSchemaFrame(reader, stack, itemDesc, (val) {
        list.add(val as T);
        index++;
      }, validate: validate);
      return false;
    } else {
      _result = list;
      stack.removeLast();
      if (stack.isNotEmpty) {
        stack.last.resume(_result);
      }
      return false;
    }
  }
}

final class _UnionFrame extends JsonParseFrame {
  final UnionDescriptor desc;
  final bool validate;
  dynamic _result;
  UnionOptionDescriptor? _pendingOption;

  _UnionFrame(this.desc, {this.validate = true});

  @override
  dynamic get result => _result;

  @override
  String? get currentPathSegment => null;

  @override
  void resume(dynamic value) {
    if (_pendingOption != null) {
      _result = _pendingOption!.wrap(value);
      _pendingOption = null;
    } else {
      _result = value;
    }
  }

  @override
  bool execute(JsonReader reader, List<JsonParseFrame> stack) {
    if (_result != null) {
      if (validate && _result is JsonModel) {
        (_result as JsonModel).validate();
      }
      stack.removeLast();
      if (stack.isNotEmpty) {
        stack.last.resume(_result);
      }
      return false;
    }

    if (desc.discriminatorProperty != null) {
      final rCopy = reader.copy();
      rCopy.expectObject();
      String? discValue;
      while (rCopy.hasNextKey()) {
        final key = rCopy.nextKey();
        if (key == desc.discriminatorProperty) {
          discValue = rCopy.expectString();
          break;
        } else {
          rCopy.skipAnyValue();
        }
      }
      if (discValue == null) {
        throw reader.fail(
          'Missing discriminator property: ${desc.discriminatorProperty}',
        );
      }
      final option = desc.discriminatorMapping?[discValue];
      if (option == null) {
        throw reader.fail('Unknown discriminator value: $discValue');
      }
      _pendingOption = option;
      _pushSchemaFrame(reader, stack, option.schema, (val) {
        _result = option.wrap(val);
        _pendingOption = null;
      }, validate: validate);
      return false;
    } else {
      FormatException? lastException;
      for (final option in desc.activeOptions) {
        final rCopy = reader.copy();
        try {
          _runNonRecursiveWithDescriptor(rCopy, option.schema, validate: false);
          _pendingOption = option;
          _pushSchemaFrame(reader, stack, option.schema, (val) {
            _result = option.wrap(val);
            _pendingOption = null;
          }, validate: validate);
          return false;
        } on FormatException catch (e) {
          lastException = e;
        }
      }
      throw reader.fail(
        'Failed to parse ${desc.title} union. Last error: ${lastException?.message}',
      );
    }
  }
}

final class _NotFrame extends JsonParseFrame {
  final NotDescriptor desc;
  final bool validate;
  dynamic _result;

  _NotFrame(this.desc, {this.validate = true});

  @override
  dynamic get result => _result;

  @override
  String? get currentPathSegment => null;

  @override
  void resume(dynamic value) {
    // Speculative parsing is done synchronously, so this should not be called.
  }

  @override
  bool execute(JsonReader reader, List<JsonParseFrame> stack) {
    if (validate) {
      final rCopy = reader.copy();
      bool matched = false;
      try {
        _runNonRecursiveWithDescriptor(rCopy, desc.inner, validate: validate);
        matched = true;
      } on JsonValidationException {
        // OK
      } on FormatException {
        // OK
      }

      if (matched) {
        throw JsonValidationException.single('Value must not match the schema');
      }
    }

    _result = readAny(reader);
    stack.removeLast();
    if (stack.isNotEmpty) {
      stack.last.resume(_result);
    }
    return false;
  }
}

SchemaDescriptor _resolve(SchemaDescriptor schema) {
  var current = schema;
  while (current is RefDescriptor) {
    current = current.target;
  }
  return current;
}

void _pushSchemaFrame(
  JsonReader reader,
  List<JsonParseFrame> stack,
  SchemaDescriptor rawSchema,
  void Function(dynamic value) onComplete, {
  required bool validate,
}) {
  final schema = _resolve(rawSchema);
  if (schema is NullableDescriptor) {
    if (reader.checkNull()) {
      reader.expectNull();
      onComplete(null);
    } else {
      _pushSchemaFrame(
        reader,
        stack,
        schema.inner,
        onComplete,
        validate: validate,
      );
    }
  } else if (schema is PrimitiveDescriptor) {
    onComplete(schema.read(reader));
  } else if (schema is AnythingDescriptor) {
    onComplete(readAny(reader));
  } else if (schema is EnumDescriptor) {
    final val = schema.base.read(reader);
    try {
      onComplete(schema.fromValue(val));
    } catch (e) {
      throw reader.fail('Invalid enum value: $val');
    }
  } else if (schema is ObjectDescriptor) {
    stack.add(_ObjectFrame(schema, validate: validate));
  } else if (schema is ArrayDescriptor) {
    stack.add(schema.createFrame(validate: validate));
  } else if (schema is UnionDescriptor) {
    stack.add(_UnionFrame(schema, validate: validate));
  } else if (schema is NotDescriptor) {
    stack.add(_NotFrame(schema, validate: validate));
  } else if (schema is NeverDescriptor) {
    throw reader.fail('Value is not allowed here');
  }
}

dynamic _runNonRecursiveWithDescriptor(
  JsonReader reader,
  SchemaDescriptor rawRootSchema, {
  bool validate = true,
}) {
  final rootSchema = _resolve(rawRootSchema);
  if (rootSchema is NullableDescriptor) {
    if (reader.checkNull()) {
      reader.expectNull();
      return null;
    }
    return _runNonRecursiveWithDescriptor(
      reader,
      rootSchema.inner,
      validate: validate,
    );
  }
  if (rootSchema is PrimitiveDescriptor) {
    return rootSchema.read(reader);
  } else if (rootSchema is AnythingDescriptor) {
    return readAny(reader);
  } else if (rootSchema is EnumDescriptor) {
    final val = rootSchema.base.read(reader);
    try {
      return rootSchema.fromValue(val);
    } catch (e) {
      throw reader.fail('Invalid enum value: $val');
    }
  }

  final rootFrame = _createFrameForSchema(rootSchema, validate: validate);
  final stack = <JsonParseFrame>[rootFrame];
  try {
    while (stack.isNotEmpty) {
      final current = stack.last;
      final isComplete = current.execute(reader, stack);
      if (isComplete) {
        stack.removeLast();
      }
    }
    return rootFrame.result;
  } on JsonValidationException catch (e) {
    final path = <String>[];
    for (final frame in stack) {
      final segment = frame.currentPathSegment;
      if (segment != null) {
        path.add(segment);
      }
    }
    final propName = path.isNotEmpty ? path.last : null;
    final updatedErrors = e.errors.map((err) {
      final updatedMsg = (propName != null && err.message.startsWith('Value '))
          ? err.message.replaceFirst('Value ', 'Property "$propName" ')
          : err.message;
      return ValidationError(
        message: updatedMsg,
        path: [...path, ...err.path],
        keyword: err.keyword,
        schema: err.schema,
        value: err.value,
        nestedErrors: err.nestedErrors,
      );
    }).toList();
    throw JsonValidationException(updatedErrors);
  } on FormatException catch (e) {
    final path = <String>[];
    for (final frame in stack) {
      final segment = frame.currentPathSegment;
      if (segment != null) {
        path.add(segment);
      }
    }
    throw wrapException(e, path);
  }
}

JsonParseFrame _createFrameForSchema(
  SchemaDescriptor rawSchema, {
  required bool validate,
}) {
  final schema = _resolve(rawSchema);
  if (schema is ObjectDescriptor) {
    return _ObjectFrame(schema, validate: validate);
  } else if (schema is ArrayDescriptor) {
    return schema.createFrame(validate: validate);
  } else if (schema is UnionDescriptor) {
    return _UnionFrame(schema, validate: validate);
  } else if (schema is NotDescriptor) {
    return _NotFrame(schema, validate: validate);
  }
  throw UnsupportedError('Primitive schemas do not require frame creation.');
}

/// Parses JSON from [reader] using the given [schema] descriptor.
///
/// If [validate] is true (default), it will validate the JSON against the
/// schema constraints during parsing.
///
/// Throws [JsonParseException] if the JSON is malformed or cannot be parsed.
/// Throws [JsonValidationException] if the JSON does not conform to the schema.
dynamic parseWithDescriptor(
  JsonReader reader,
  SchemaDescriptor schema, {
  bool validate = true,
}) {
  return _runNonRecursiveWithDescriptor(reader, schema, validate: validate);
}

/// Writes [value] to [sink] using the given [schema] descriptor.
///
/// The [value] must match the structure expected by the [schema] descriptor.
///
/// Throws [ArgumentError] if the value cannot be serialized.
void writeWithDescriptor<T>(
  JsonSink sink,
  T value,
  SchemaDescriptor<T> schema,
) {
  _writeSchemaValue(sink, value, schema);
}

void _writeSchemaValue(
  JsonSink sink,
  Object? value,
  SchemaDescriptor rawSchema,
) {
  final schema = _resolve(rawSchema);
  if (schema is NullableDescriptor) {
    if (value == null) {
      sink.addNull();
    } else {
      _writeSchemaValue(sink, value, schema.inner);
    }
    return;
  }
  if (schema is PrimitiveDescriptor) {
    schema.write(sink, value);
  } else if (schema is AnythingDescriptor) {
    writeAny(sink, value);
  } else if (schema is NotDescriptor) {
    writeAny(sink, value);
  } else if (schema is EnumDescriptor) {
    final backingVal = schema.toValue(value);
    schema.base.write(sink, backingVal);
  } else if (schema is ArrayDescriptor) {
    sink.startArray();
    if (value is List) {
      for (var i = 0; i < value.length; i++) {
        final item = value[i];
        final itemSchema =
            (schema.prefixItems != null && i < schema.prefixItems!.length)
            ? schema.prefixItems![i]
            : schema.items;
        _writeSchemaValue(sink, item, itemSchema);
      }
    }
    sink.endArray();
  } else if (schema is ObjectDescriptor) {
    sink.startObject();
    final fields = schema.getFields(value);
    schema.properties.forEach((key, prop) {
      if (fields.containsKey(key)) {
        final val = fields[key];
        sink.addKey(key);
        _writeSchemaValue(sink, val, prop.schema);
      }
    });
    fields.forEach((key, val) {
      if (schema.properties.containsKey(key)) return;

      final matchingPatterns = schema.patternProperties.entries
          .where((e) => e.key.hasMatch(key))
          .toList();
      if (matchingPatterns.isNotEmpty) {
        sink.addKey(key);
        _writeSchemaValue(sink, val, matchingPatterns.first.value);
      } else if (schema.additionalProperties != null &&
          schema.additionalProperties is! NeverDescriptor) {
        sink.addKey(key);
        _writeSchemaValue(sink, val, schema.additionalProperties!);
      }
    });
    sink.endObject();
  } else if (schema is UnionDescriptor) {
    if (value is JsonWritable) {
      value.writeJson(sink);
    } else {
      var found = false;
      for (final option in schema.activeOptions) {
        if (_descriptorMatches(option.schema, value)) {
          _writeSchemaValue(sink, value, option.schema);
          found = true;
          break;
        }
      }
      if (!found) {
        throw ArgumentError(
          'Value $value does not match any option of union ${schema.title}',
        );
      }
    }
  }
}

bool _descriptorMatches(SchemaDescriptor rawSchema, Object? value) {
  final schema = _resolve(rawSchema);
  if (schema is NullableDescriptor) {
    if (value == null) return true;
    return _descriptorMatches(schema.inner, value);
  }
  if (schema is StringDescriptor) {
    return value is String;
  }
  if (schema is IntDescriptor) {
    return value is int;
  }
  if (schema is NumDescriptor) {
    return value is num;
  }
  if (schema is BoolDescriptor) {
    return value is bool;
  }
  if (schema is NullDescriptor) {
    return value == null;
  }
  if (schema is AnythingDescriptor) {
    return true;
  }
  if (schema is NeverDescriptor) {
    return false;
  }
  if (schema is ArrayDescriptor) {
    return value is List;
  }
  if (schema is ObjectDescriptor) {
    return schema.matches(value);
  }
  if (schema is EnumDescriptor) {
    return schema.values.contains(value);
  }
  if (schema is UnionDescriptor) {
    for (final option in schema.activeOptions) {
      if (_descriptorMatches(option.schema, value)) {
        return true;
      }
    }
    return false;
  }
  return false;
}

/// Validates if a string is a valid hostname according to RFC 1034.
///
/// A hostname must be at most 253 characters long.
/// Labels must be separated by dots and be at most 63 characters long,
/// containing only alphanumeric characters and hyphens, and not starting
/// or ending with a hyphen.
bool isValidHostname(String s) {
  if (s.length > 253) return false;
  final labelRegex = RegExp(
    r'^([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])$',
  );
  final labels = s.split('.');
  for (final label in labels) {
    if (!labelRegex.hasMatch(label)) return false;
  }
  return true;
}

/// Validates if a string is a valid IPv6 address according to RFC 3986.
bool isValidIPv6(String s) {
  final ipv6Regex = RegExp(
    r'^((([0-9A-Fa-f]{1,4}:){7}[0-9A-Fa-f]{1,4})|'
    r'(([0-9A-Fa-f]{1,4}:){1,7}:)|'
    r'(([0-9A-Fa-f]{1,4}:){1,6}:[0-9A-Fa-f]{1,4})|'
    r'(([0-9A-Fa-f]{1,4}:){1,5}:([0-9A-Fa-f]{1,4}:){1,2}[0-9A-Fa-f]{1,4})|'
    r'(([0-9A-Fa-f]{1,4}:){1,4}:([0-9A-Fa-f]{1,4}:){1,3}[0-9A-Fa-f]{1,4})|'
    r'(([0-9A-Fa-f]{1,4}:){1,3}:([0-9A-Fa-f]{1,4}:){1,4}[0-9A-Fa-f]{1,4})|'
    r'(([0-9A-Fa-f]{1,4}:){1,2}:([0-9A-Fa-f]{1,4}:){1,5}[0-9A-Fa-f]{1,4})|'
    r'([0-9A-Fa-f]{1,4}::([0-9A-Fa-f]{1,4}:){1,6}[0-9A-Fa-f]{1,4})|'
    r'(:(:([0-9A-Fa-f]{1,4}:){0,7}[0-9A-Fa-f]{1,4}|:))|'
    r'(fe80:(:[0-9A-Fa-f]{1,4}){0,4}%[0-9a-zA-Z]{1,})|'
    r'(::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))|'
    r'(([0-9A-Fa-f]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])))$',
  );
  return ipv6Regex.hasMatch(s);
}

/// Validates if a string is a valid time string (HH:MM:SS.sss) according to RFC 3339.
bool isValidTime(String s) {
  final timeRegex = RegExp(
    r'^([01][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?([zZ]|[+-](?:[01][0-9]|2[0-3]):[0-5][0-9])$',
  );
  return timeRegex.hasMatch(s);
}

/// Validates if a string is a valid URI reference according to RFC 3986.
bool isValidUriReference(String s) {
  if (Uri.tryParse(s) == null) return false;
  final allowedChars = RegExp(r"^[A-Za-z0-9\-._~:/?#\[\]@!$&'()*+,;=%]*$");
  if (!allowedChars.hasMatch(s)) return false;

  final percentCheck = RegExp(r'%[0-9a-fA-F]{2}');
  var index = 0;
  while ((index = s.indexOf('%', index)) != -1) {
    if (index + 2 >= s.length) return false;
    final part = s.substring(index, index + 3);
    if (!percentCheck.hasMatch(part)) return false;
    index += 3;
  }
  return true;
}

/// Validates if a string is a valid absolute URI according to RFC 3986.
bool isValidUri(String s) {
  if (!isValidUriReference(s)) return false;
  final parsed = Uri.tryParse(s);
  return parsed != null && parsed.hasScheme;
}

/// Validates if a string is a valid duration according to RFC 3339 Appendix A.
bool isValidDuration(String s) {
  if (s == 'P' || s.endsWith('T')) return false;
  final exp = RegExp(
    r'^P(?:(\d+W)|(?:(\d+Y(?:(\d+M)(\d+D)?)?|\d+M(?:\d+D)?|\d+D)?(?:T(\d+H(?:(\d+M)(\d+S)?)?|\d+M(?:\d+S)?|\d+S))?))$',
  );
  return exp.hasMatch(s);
}

/// Validates if a string is a valid JSON Pointer according to RFC 6901.
bool isValidJsonPointer(String s) {
  final exp = RegExp(r'^(?:/(?:[^~/]|~0|~1)*)*$');
  return exp.hasMatch(s);
}

/// Validates if a string is a valid Relative JSON Pointer according to draft-handrews-relative-json-pointer-01.
bool isValidRelativeJsonPointer(String s) {
  final exp = RegExp(r'^(?:0|[1-9]\d*)(?:#|(?:/(?:[^~/]|~0|~1)*)*)$');
  return exp.hasMatch(s);
}

/// Validates if a string is a valid URI Template according to RFC 6570.
bool isValidUriTemplate(String s) {
  final exp = RegExp(r'^([^{}]|\{[^{}]+\})*$');
  return exp.hasMatch(s);
}

/// Validates if a string is a valid IRI according to RFC 3987.
bool isValidIri(String s) {
  final parsed = Uri.tryParse(s);
  return parsed != null && parsed.hasScheme;
}

/// Validates if a string is a valid IRI Reference according to RFC 3987.
bool isValidIriReference(String s) {
  return Uri.tryParse(s) != null;
}

/// Validates if a string is a valid IDN Email according to RFC 6531 / 5322.
bool isValidIdnEmail(String s) {
  final exp = RegExp(r'^[^@\s]+@[^@\s]+\.[^@\s]+$');
  return exp.hasMatch(s);
}

/// Validates if a string is a valid IDN Hostname according to RFC 5890.
bool isValidIdnHostname(String s) {
  if (s.isEmpty || s.length > 253) return false;
  final labels = s.split('.');
  for (final label in labels) {
    if (label.isEmpty || label.length > 63) return false;
    if (label.startsWith('-') || label.endsWith('-')) return false;
  }
  return true;
}

/// Extension on [Schema] to support runtime validation.
///
/// {@example /example/lib/manual_validation.dart}
extension SchemaValidationExtension on Schema {
  /// Validates [value] against this schema.
  ///
  /// Throws [JsonValidationException] containing all errors if validation fails.
  /// If [failFast] is `false` (the default), validation continues to accumulate all
  /// errors and throws a [JsonValidationException] containing all errors in [JsonValidationException.errors].
  /// If [failFast] is `true`, validation halts at the first error.
  void validate(
    dynamic value, {
    bool validateFormats = false,
    bool failFast = false,
  }) {
    final context = _ValidationContext(
      failFast: failFast,
      validateFormats: validateFormats,
      dynamicAnchors: dynamicAnchors ?? const {},
    );
    try {
      const _Validator().validate(value, this, _ValidationPath.empty, context);
    } on _ValidationAbortException {
      // Short-circuited on first error in fail-fast mode
    }
    if (context.hasErrors) {
      throw JsonValidationException(context.errors);
    }
  }

  /// Validates [value] against this schema and returns all accumulated errors.
  ///
  /// Never throws [JsonValidationException]. Returns an empty list if the value is valid.
  List<ValidationError> collectErrors(
    dynamic value, {
    bool validateFormats = false,
  }) {
    final context = _ValidationContext(
      failFast: false,
      validateFormats: validateFormats,
      dynamicAnchors: dynamicAnchors ?? const {},
    );
    const _Validator().validate(value, this, _ValidationPath.empty, context);
    return List.unmodifiable(context.errors);
  }
}

/// Creates a validator function for the given JSON [schema].
///
/// The returned function takes a decoded JSON value and validates it.
/// It throws [JsonValidationException] if validation fails.
Future<void Function(dynamic)> createValidator(
  Map<String, dynamic> schema, {
  Future<List<int>> Function(Uri uri)? uriResolver,
  bool disallowExternalRefs = true,
  bool flatten = false,
  bool validateFormats = false,
  bool failFast = false,
}) async {
  final parser = SchemaParser(
    schema,
    uriResolver: uriResolver,
    disallowExternalRefs: disallowExternalRefs,
    flatten: flatten,
  );
  final parsedSchema = await parser.parse();
  return (dynamic value) => parsedSchema.validate(
    value,
    validateFormats: validateFormats,
    failFast: failFast,
  );
}

/// Creates an error-collecting validator function for the given JSON [schema].
///
/// The returned function takes a decoded JSON value, validates it, and returns
/// a list of all accumulated [ValidationError]s without throwing.
Future<List<ValidationError> Function(dynamic)> createErrorCollector(
  Map<String, dynamic> schema, {
  Future<List<int>> Function(Uri uri)? uriResolver,
  bool disallowExternalRefs = true,
  bool flatten = false,
  bool validateFormats = false,
}) async {
  final parser = SchemaParser(
    schema,
    uriResolver: uriResolver,
    disallowExternalRefs: disallowExternalRefs,
    flatten: flatten,
  );
  final parsedSchema = await parser.parse();
  return (dynamic value) =>
      parsedSchema.collectErrors(value, validateFormats: validateFormats);
}

abstract class _ValidationPath {
  static const _ValidationPath empty = _EmptyPath();
  _ValidationPath append(Object segment);
  List<String> toList();
}

class _EmptyPath implements _ValidationPath {
  const _EmptyPath();
  @override
  _ValidationPath append(Object segment) => _SegmentPath(this, segment);
  @override
  List<String> toList() => const [];
}

class _SegmentPath implements _ValidationPath {
  final _ValidationPath parent;
  final Object segment;
  _SegmentPath(this.parent, this.segment);

  @override
  _ValidationPath append(Object segment) => _SegmentPath(this, segment);

  @override
  List<String> toList() {
    final result = <String>[];
    _build(result);
    return result;
  }

  void _build(List<String> list) {
    if (parent is _SegmentPath) {
      (parent as _SegmentPath)._build(list);
    }
    list.add(segment.toString());
  }
}

class _EvaluationTracker {
  final Set<String> evaluatedProperties = {};
  final Set<int> evaluatedItems = {};

  _EvaluationTracker();

  void merge(_EvaluationTracker other) {
    evaluatedProperties.addAll(other.evaluatedProperties);
    evaluatedItems.addAll(other.evaluatedItems);
  }
}

class _ValidationAbortException implements Exception {
  const _ValidationAbortException();

  @override
  String toString() => '_ValidationAbortException';
}

class _ValidationContext {
  final List<ValidationError> errors = [];
  final bool failFast;
  final bool validateFormats;
  final Map<String, Schema> dynamicAnchors;
  final List<String> dynamicScope;

  _ValidationContext({
    this.failFast = false,
    this.validateFormats = false,
    this.dynamicAnchors = const {},
    List<String>? dynamicScope,
  }) : dynamicScope = dynamicScope ?? [];

  bool get hasErrors => errors.isNotEmpty;

  void addError(
    String message,
    _ValidationPath path, {
    String? keyword,
    Schema? schema,
    dynamic value,
    List<ValidationError> nestedErrors = const [],
  }) {
    errors.add(
      ValidationError(
        message: message,
        path: path.toList(),
        keyword: keyword,
        schema: schema,
        value: value,
        nestedErrors: nestedErrors,
      ),
    );
    if (failFast) {
      throw const _ValidationAbortException();
    }
  }

  _ValidationContext createBranch({bool? failFast}) {
    return _ValidationContext(
      failFast: failFast ?? this.failFast,
      validateFormats: validateFormats,
      dynamicAnchors: dynamicAnchors,
      dynamicScope: List.of(dynamicScope),
    );
  }
}

class _Validator {
  const _Validator();

  _EvaluationTracker validate(
    dynamic value,
    Schema schema,
    _ValidationPath path,
    _ValidationContext context,
  ) {
    final tracker = _EvaluationTracker();

    if (schema.isNever) {
      context.addError(
        'Value matches "never" schema',
        path,
        keyword: 'false',
        schema: schema,
        value: value,
      );
      return tracker;
    }

    if (schema.isAnything) {
      return tracker;
    }

    final vocabs = schema.vocabularies;
    final hasValidation = vocabs == null || vocabs.contains(_vocabValidation);
    final hasApplicator = vocabs == null || vocabs.contains(_vocabApplicator);

    final resourceUri = schema.resourceUri;
    final pushed =
        resourceUri != null &&
        (context.dynamicScope.isEmpty ||
            context.dynamicScope.last != resourceUri);
    if (pushed) {
      context.dynamicScope.add(resourceUri);
    }

    try {
      // Check 'not'
      if (hasApplicator && schema.not != null) {
        final branch = context.createBranch(failFast: true);
        try {
          validate(value, schema.not!, path, branch);
        } on _ValidationAbortException {
          // Failure in branch means 'not' condition succeeded
        }
        if (!branch.hasErrors) {
          context.addError(
            'Value must not match the schema',
            path,
            keyword: 'not',
            schema: schema,
            value: value,
          );
        }
      }

      // Resolve ref / dynamicRef
      if (schema.ref != null || schema.dynamicRef != null) {
        Schema? target;
        if (schema.dynamicRef != null) {
          final lexicalTarget = schema.realSchema;
          final refUri = Uri.parse(schema.dynamicRef!);
          final anchor = refUri.fragment;
          if (anchor.isNotEmpty && lexicalTarget.dynamicAnchor == anchor) {
            for (final uri in context.dynamicScope) {
              final targetUri = Uri.parse(
                uri,
              ).replace(fragment: anchor).toString();
              if (context.dynamicAnchors.containsKey(targetUri)) {
                target = context.dynamicAnchors[targetUri];
                break;
              }
            }
          }
          target ??= lexicalTarget;
        } else {
          target = schema.resolvedRef!;
        }

        final refTracker = validate(value, target, path, context);
        tracker.merge(refTracker);
      }

      if (hasValidation) {
        // Type validation
        if (schema.type != null) {
          _validateType(
            value,
            schema.type!,
            schema.hasExplicitType,
            path,
            context,
            schema: schema,
          );
        }

        // Enum validation
        if (schema.enumValues != null) {
          if (!schema.enumValues!.any((v) => deepEquals(v, value))) {
            context.addError(
              'Value must be one of: ${schema.enumValues}',
              path,
              keyword: 'enum',
              schema: schema,
              value: value,
            );
          }
        }

        // Const validation
        if (schema.constValue != null) {
          if (!deepEquals(schema.constValue, value)) {
            context.addError(
              'Value must be const: ${schema.constValue}',
              path,
              keyword: 'const',
              schema: schema,
              value: value,
            );
          }
        }
      }

      // Object validation
      if (value is Map) {
        final objTracker = _validateObject(value, schema, path, this, context);
        tracker.merge(objTracker);
      }

      // Array validation
      if (value is List) {
        final arrTracker = _validateArray(value, schema, path, this, context);
        tracker.merge(arrTracker);
      }

      // String validation
      if (value is String) {
        _validateString(
          value,
          schema,
          path,
          context,
          validateFormats: context.validateFormats,
        );
      }

      // Number validation
      if (value is num) {
        _validateNumber(value, schema, path, context);
      }

      // Combinators
      if (hasApplicator) {
        if (schema.discriminator != null) {
          if (value is! Map) {
            context.addError(
              'Value must be an object for discriminator validation',
              path,
              keyword: 'discriminator',
              schema: schema,
              value: value,
            );
            return tracker;
          }
          final propName = schema.discriminator!.propertyName;
          final discValue = value[propName];
          if (discValue == null) {
            context.addError(
              'Missing discriminator property: $propName',
              path,
              keyword: 'discriminator',
              schema: schema,
              value: value,
            );
            return tracker;
          }
          if (discValue is! String) {
            context.addError(
              'Discriminator property $propName must be a string',
              path,
              keyword: 'discriminator',
              schema: schema,
              value: discValue,
            );
            return tracker;
          }
          final targetSchema = schema.discriminator!.mapping?[discValue];
          if (targetSchema == null) {
            context.addError(
              'Unknown discriminator value: $discValue',
              path,
              keyword: 'discriminator',
              schema: schema,
              value: discValue,
            );
            return tracker;
          }
          final subTracker = validate(value, targetSchema, path, context);
          tracker.merge(subTracker);
          return tracker;
        }

        if (schema.allOf != null) {
          for (final sub in schema.allOf!) {
            final subTracker = validate(value, sub, path, context);
            tracker.merge(subTracker);
          }
        }

        if (schema.anyOf != null) {
          bool anyValid = false;
          final mergedTracker = _EvaluationTracker();
          final allBranchErrors = <ValidationError>[];
          for (final sub in schema.anyOf!) {
            final branch = context.createBranch(failFast: true);
            try {
              final subTracker = validate(value, sub, path, branch);
              anyValid = true;
              mergedTracker.merge(subTracker);
            } on _ValidationAbortException {
              allBranchErrors.addAll(branch.errors);
            }
          }
          if (!anyValid) {
            context.addError(
              'Value does not match any of the subschemas. Errors: $allBranchErrors',
              path,
              keyword: 'anyOf',
              schema: schema,
              value: value,
              nestedErrors: allBranchErrors,
            );
          } else {
            tracker.merge(mergedTracker);
          }
        }

        if (schema.oneOf != null) {
          int validCount = 0;
          _EvaluationTracker? singleTracker;
          final allBranchErrors = <ValidationError>[];
          for (final sub in schema.oneOf!) {
            final branch = context.createBranch(failFast: true);
            try {
              final subTracker = validate(value, sub, path, branch);
              validCount++;
              singleTracker = subTracker;
            } on _ValidationAbortException {
              allBranchErrors.addAll(branch.errors);
            }
          }
          if (validCount != 1) {
            final message = validCount == 0
                ? 'Value must match exactly one subschema (matched 0). Errors: $allBranchErrors'
                : 'Value must match exactly one subschema (matched $validCount)';
            context.addError(
              message,
              path,
              keyword: 'oneOf',
              schema: schema,
              value: value,
              nestedErrors: validCount == 0 ? allBranchErrors : const [],
            );
          } else {
            tracker.merge(singleTracker!);
          }
        }

        if (schema.ifSchema != null) {
          final ifBranch = context.createBranch(failFast: true);
          _EvaluationTracker? ifTracker;
          try {
            ifTracker = validate(value, schema.ifSchema!, path, ifBranch);
          } on _ValidationAbortException {
            // Condition did not match; ifBranch.hasErrors is true
          }

          if (!ifBranch.hasErrors) {
            tracker.merge(ifTracker!);
            if (schema.thenSchema != null) {
              final thenTracker = validate(
                value,
                schema.thenSchema!,
                path,
                context,
              );
              tracker.merge(thenTracker);
            }
          } else {
            if (schema.elseSchema != null) {
              final elseTracker = validate(
                value,
                schema.elseSchema!,
                path,
                context,
              );
              tracker.merge(elseTracker);
            }
          }
        }

        // Unevaluated validation
        if (value is Map && schema.unevaluatedProperties != null) {
          value.forEach((key, val) {
            if (!tracker.evaluatedProperties.contains(key)) {
              validate(
                val,
                schema.unevaluatedProperties!,
                path.append(key as Object),
                context,
              );
              tracker.evaluatedProperties.add(key.toString());
            }
          });
        }

        if (value is List && schema.unevaluatedItems != null) {
          value.asMap().forEach((index, val) {
            if (!tracker.evaluatedItems.contains(index)) {
              validate(
                val,
                schema.unevaluatedItems!,
                path.append(index),
                context,
              );
              tracker.evaluatedItems.add(index);
            }
          });
        }
      }
    } finally {
      if (pushed) {
        context.dynamicScope.removeLast();
      }
    }

    return tracker;
  }
}

void _validateType(
  dynamic value,
  List<String> allowedTypes,
  bool hasExplicitType,
  _ValidationPath path,
  _ValidationContext context, {
  Schema? schema,
}) {
  bool matches = false;
  for (final type in allowedTypes) {
    if (type == 'null' && value == null) matches = true;
    if (type == 'boolean' && value is bool) matches = true;
    if (type == 'string' && value is String) matches = true;
    if (type == 'number' && value is num) matches = true;
    if (type == 'integer' && value is num) {
      if (value is int || value == value.toInt()) {
        matches = true;
      }
    }
    if (type == 'object' && value is Map) matches = true;
    if (type == 'array' && value is List) matches = true;
  }
  if (!matches) {
    if (hasExplicitType) {
      context.addError(
        'Value must be one of type: $allowedTypes',
        path,
        keyword: 'type',
        schema: schema,
        value: value,
      );
    }
  }
}

void _validateNumber(
  dynamic value,
  Schema schema,
  _ValidationPath path,
  _ValidationContext context,
) {
  if (schema.vocabularies != null &&
      !schema.vocabularies!.contains(_vocabValidation)) {
    return;
  }
  if (value is! num) {
    if (schema.hasExplicitType) {
      context.addError(
        'Value must be a number',
        path,
        keyword: 'type',
        schema: schema,
        value: value,
      );
    }
    return;
  }
  if (schema.isInteger) {
    if (value is! int && value != value.toInt()) {
      context.addError(
        'Value must be an integer',
        path,
        keyword: 'type',
        schema: schema,
        value: value,
      );
    }
  }

  final val = value;
  if (schema.minimum != null && val < schema.minimum!) {
    context.addError(
      'Value must be >= ${schema.minimum}',
      path,
      keyword: 'minimum',
      schema: schema,
      value: val,
    );
  }
  if (schema.maximum != null && val > schema.maximum!) {
    context.addError(
      'Value must be <= ${schema.maximum}',
      path,
      keyword: 'maximum',
      schema: schema,
      value: val,
    );
  }
  if (schema.exclusiveMinimum != null && val <= schema.exclusiveMinimum!) {
    context.addError(
      'Value must be > ${schema.exclusiveMinimum}',
      path,
      keyword: 'exclusiveMinimum',
      schema: schema,
      value: val,
    );
  }
  if (schema.exclusiveMaximum != null && val >= schema.exclusiveMaximum!) {
    context.addError(
      'Value must be < ${schema.exclusiveMaximum}',
      path,
      keyword: 'exclusiveMaximum',
      schema: schema,
      value: val,
    );
  }
  if (schema.multipleOf != null) {
    final valInt = parseInt(val);
    final mInt = parseInt(schema.multipleOf);
    if (valInt != null && mInt != null) {
      if (valInt % mInt != 0) {
        context.addError(
          'Value must be a multiple of ${schema.multipleOf}',
          path,
          keyword: 'multipleOf',
          schema: schema,
          value: val,
        );
      }
    } else {
      final div = val / schema.multipleOf!;
      if (!div.isFinite) {
        context.addError(
          'Value must be a multiple of ${schema.multipleOf}',
          path,
          keyword: 'multipleOf',
          schema: schema,
          value: val,
        );
      } else {
        final rounded = div.round();
        final absError = (div - rounded).abs();
        final relError = absError / math.max(div.abs(), 1.0);
        if (relError > 1e-14) {
          context.addError(
            'Value must be a multiple of ${schema.multipleOf}',
            path,
            keyword: 'multipleOf',
            schema: schema,
            value: val,
          );
        }
      }
    }
  }
}

void _validateString(
  dynamic value,
  Schema schema,
  _ValidationPath path,
  _ValidationContext context, {
  bool validateFormats = false,
}) {
  if (schema.vocabularies != null &&
      !schema.vocabularies!.contains(_vocabValidation)) {
    return;
  }
  if (value is! String) {
    if (schema.hasExplicitType) {
      context.addError(
        'Value must be a string',
        path,
        keyword: 'type',
        schema: schema,
        value: value,
      );
    }
    return;
  }
  // JSON Schema counts Unicode code points, not grapheme clusters.
  if (schema.minLength != null && value.runes.length < schema.minLength!) {
    context.addError(
      'Value length must be >= ${schema.minLength}',
      path,
      keyword: 'minLength',
      schema: schema,
      value: value,
    );
  }
  // JSON Schema counts Unicode code points, not grapheme clusters.
  if (schema.maxLength != null && value.runes.length > schema.maxLength!) {
    context.addError(
      'Value length must be <= ${schema.maxLength}',
      path,
      keyword: 'maxLength',
      schema: schema,
      value: value,
    );
  }
  if (schema.pattern != null) {
    final regExp = RegExp(schema.pattern!, unicode: true);
    if (!regExp.hasMatch(value)) {
      context.addError(
        'Value must match pattern: ${schema.pattern}',
        path,
        keyword: 'pattern',
        schema: schema,
        value: value,
      );
    }
  }
  if (schema.format != null && validateFormats) {
    switch (schema.format) {
      case 'date-time':
        final r = RegExp(
          r'^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})?$',
        );
        if (!r.hasMatch(value)) {
          context.addError(
            'Value must be a valid date-time string',
            path,
            keyword: 'format',
            schema: schema,
            value: value,
          );
        }
        break;
      case 'email':
        final r = RegExp(r'^[^@]+@[^@]+\.[^@]+$');
        if (!r.hasMatch(value)) {
          context.addError(
            'Value must be a valid email address',
            path,
            keyword: 'format',
            schema: schema,
            value: value,
          );
        }
      case 'duration':
        if (!isValidDuration(value)) {
          context.addError(
            'Value must be a valid RFC 3339 duration',
            path,
            keyword: 'format',
            schema: schema,
            value: value,
          );
        }
        break;
      case 'json-pointer':
        if (!isValidJsonPointer(value)) {
          context.addError(
            'Value must be a valid JSON pointer',
            path,
            keyword: 'format',
            schema: schema,
            value: value,
          );
        }
        break;
      case 'relative-json-pointer':
        if (!isValidRelativeJsonPointer(value)) {
          context.addError(
            'Value must be a valid relative JSON pointer',
            path,
            keyword: 'format',
            schema: schema,
            value: value,
          );
        }
        break;
      case 'uri-template':
        if (!isValidUriTemplate(value)) {
          context.addError(
            'Value must be a valid URI template',
            path,
            keyword: 'format',
            schema: schema,
            value: value,
          );
        }
        break;
      case 'iri':
        if (!isValidIri(value)) {
          context.addError(
            'Value must be a valid IRI',
            path,
            keyword: 'format',
            schema: schema,
            value: value,
          );
        }
        break;
      case 'iri-reference':
        if (!isValidIriReference(value)) {
          context.addError(
            'Value must be a valid IRI reference',
            path,
            keyword: 'format',
            schema: schema,
            value: value,
          );
        }
        break;
      case 'idn-email':
        if (!isValidIdnEmail(value)) {
          context.addError(
            'Value must be a valid IDN email',
            path,
            keyword: 'format',
            schema: schema,
            value: value,
          );
        }
        break;
      case 'idn-hostname':
        if (!isValidIdnHostname(value)) {
          context.addError(
            'Value must be a valid IDN hostname',
            path,
            keyword: 'format',
            schema: schema,
            value: value,
          );
        }
        break;
      case 'hostname':
        final r = RegExp(
          r'^([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])'
          r'(\.([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9]))*$',
        );
        if (!r.hasMatch(value) || value.length > 255) {
          context.addError(
            'Value must be a valid hostname',
            path,
            keyword: 'format',
            schema: schema,
            value: value,
          );
        }
        break;
      case 'ipv4':
        final r = RegExp(
          r'^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}'
          r'(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$',
        );
        if (!r.hasMatch(value)) {
          context.addError(
            'Value must be a valid IPv4 address',
            path,
            keyword: 'format',
            schema: schema,
            value: value,
          );
        }
        break;
      case 'ipv6':
        final r = RegExp(r'^([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}$');
        final r2 = RegExp(
          r'^((?:[0-9A-Fa-f]{1,4}(?::[0-9A-Fa-f]{1,4})*)?)::'
          r'((?:[0-9A-Fa-f]{1,4}(?::[0-9A-Fa-f]{1,4})*)?)$',
        );
        if (!r.hasMatch(value) && !r2.hasMatch(value)) {
          context.addError(
            'Value must be a valid IPv6 address',
            path,
            keyword: 'format',
            schema: schema,
            value: value,
          );
        }
        break;
      case 'uri':
        try {
          final uri = Uri.parse(value);
          if (!uri.hasScheme) {
            context.addError(
              'Value must be a valid URI (missing scheme)',
              path,
              keyword: 'format',
              schema: schema,
              value: value,
            );
          }
        } catch (e) {
          context.addError(
            'Value must be a valid URI',
            path,
            keyword: 'format',
            schema: schema,
            value: value,
          );
        }
        break;
      case 'uri-reference':
        if (!isValidUriReference(value)) {
          context.addError(
            'Value must be a valid URI reference',
            path,
            keyword: 'format',
            schema: schema,
            value: value,
          );
        }
        break;
      case 'uuid':
        final r = RegExp(
          r'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-'
          r'[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
        );
        if (!r.hasMatch(value)) {
          context.addError(
            'Value must be a valid UUID',
            path,
            keyword: 'format',
            schema: schema,
            value: value,
          );
        }
        break;
      case 'regex':
        try {
          RegExp(value);
        } catch (e) {
          context.addError(
            'Value must be a valid regular expression',
            path,
            keyword: 'format',
            schema: schema,
            value: value,
          );
        }
        break;
      case 'date':
        final r = RegExp(r'^\d{4}-\d{2}-\d{2}$');
        if (!r.hasMatch(value)) {
          context.addError(
            'Value must be a valid date string',
            path,
            keyword: 'format',
            schema: schema,
            value: value,
          );
        }
        break;
      case 'time':
        if (!isValidTime(value)) {
          context.addError(
            'Value must be a valid time string',
            path,
            keyword: 'format',
            schema: schema,
            value: value,
          );
        }
        break;
    }
  }
}

_EvaluationTracker _validateArray(
  dynamic value,
  Schema schema,
  _ValidationPath path,
  _Validator validator,
  _ValidationContext context,
) {
  final tracker = _EvaluationTracker();
  if (value is! List) return tracker;
  final list = value;

  final vocabs = schema.vocabularies;
  final hasValidation = vocabs == null || vocabs.contains(_vocabValidation);
  final hasApplicator = vocabs == null || vocabs.contains(_vocabApplicator);

  if (hasValidation) {
    if (schema.minItems != null && list.length < schema.minItems!) {
      context.addError(
        'Value must have >= ${schema.minItems} items',
        path,
        keyword: 'minItems',
        schema: schema,
        value: value,
      );
    }
    if (schema.maxItems != null && list.length > schema.maxItems!) {
      context.addError(
        'Value must have <= ${schema.maxItems} items',
        path,
        keyword: 'maxItems',
        schema: schema,
        value: value,
      );
    }

    if (schema.uniqueItems == true) {
      bool duplicateFound = false;
      for (var i = 0; i < list.length && !duplicateFound; i++) {
        for (var j = i + 1; j < list.length; j++) {
          if (deepEquals(list[i], list[j])) {
            context.addError(
              'Value must have unique items, but items at indices $i and $j are equal',
              path,
              keyword: 'uniqueItems',
              schema: schema,
              value: value,
            );
            duplicateFound = true;
            break;
          }
        }
      }
    }
  }

  var prefixItemsCount = 0;
  if (hasApplicator) {
    if (schema.prefixItems != null) {
      prefixItemsCount = schema.prefixItems!.length;
      for (var i = 0; i < math.min(list.length, prefixItemsCount); i++) {
        validator.validate(
          list[i],
          schema.prefixItems![i],
          path.append(i),
          context,
        );
        tracker.evaluatedItems.add(i);
      }
    }

    if (schema.items != null) {
      for (var i = prefixItemsCount; i < list.length; i++) {
        validator.validate(list[i], schema.items!, path.append(i), context);
        tracker.evaluatedItems.add(i);
      }
    }

    if (schema.contains != null) {
      var containsCount = 0;
      for (var i = 0; i < list.length; i++) {
        final branch = context.createBranch(failFast: true);
        try {
          validator.validate(list[i], schema.contains!, path.append(i), branch);
          containsCount++;
          tracker.evaluatedItems.add(i);
        } on _ValidationAbortException {
          // Item did not match contains schema
        }
      }

      final minContains = hasValidation ? (schema.minContains ?? 1) : 1;
      if (containsCount < minContains) {
        context.addError(
          'Value must contain at least $minContains items matching contains schema (matched $containsCount)',
          path,
          keyword: schema.minContains != null ? 'minContains' : 'contains',
          schema: schema,
          value: value,
        );
      }
      if (hasValidation &&
          schema.maxContains != null &&
          containsCount > schema.maxContains!) {
        context.addError(
          'Value must contain at most ${schema.maxContains} items matching contains schema',
          path,
          keyword: 'maxContains',
          schema: schema,
          value: value,
        );
      }
    }
  }

  return tracker;
}

_EvaluationTracker _validateObject(
  dynamic value,
  Schema schema,
  _ValidationPath path,
  _Validator validator,
  _ValidationContext context,
) {
  final tracker = _EvaluationTracker();
  if (value is! Map) return tracker;
  final map = value;

  final vocabs = schema.vocabularies;
  final hasValidation = vocabs == null || vocabs.contains(_vocabValidation);
  final hasApplicator = vocabs == null || vocabs.contains(_vocabApplicator);

  if (hasValidation) {
    if (schema.required != null) {
      for (final req in schema.required!) {
        if (!map.containsKey(req)) {
          context.addError(
            'Missing required property: $req',
            path.append(req),
            keyword: 'required',
            schema: schema,
            value: value,
          );
        }
      }
    }

    if (schema.minProperties != null && map.length < schema.minProperties!) {
      context.addError(
        'Object must have >= ${schema.minProperties} properties',
        path,
        keyword: 'minProperties',
        schema: schema,
        value: value,
      );
    }
    if (schema.maxProperties != null && map.length > schema.maxProperties!) {
      context.addError(
        'Object must have <= ${schema.maxProperties} properties',
        path,
        keyword: 'maxProperties',
        schema: schema,
        value: value,
      );
    }
  }

  map.forEach((key, val) {
    if (key is! String) {
      context.addError(
        'Object keys must be strings',
        path,
        keyword: 'propertyNames',
        schema: schema,
        value: key,
      );
      return;
    }

    if (hasApplicator && schema.propertyNames != null) {
      validator.validate(key, schema.propertyNames!, path.append(key), context);
    }

    var evaluated = false;

    if (hasApplicator) {
      if (schema.properties != null) {
        final propSchema = schema.properties![key];
        if (propSchema != null) {
          validator.validate(val, propSchema, path.append(key), context);
          tracker.evaluatedProperties.add(key);
          evaluated = true;
        }
      }

      if (schema.patternProperties != null) {
        schema.patternProperties!.forEach((pattern, patternSchema) {
          if (pattern.hasMatch(key)) {
            validator.validate(val, patternSchema, path.append(key), context);
            tracker.evaluatedProperties.add(key);
            evaluated = true;
          }
        });
      }

      if (!evaluated) {
        final addProps = schema.additionalProperties;
        if (addProps != null) {
          validator.validate(val, addProps, path.append(key), context);
          tracker.evaluatedProperties.add(key);
        }
      }
    }
  });

  if (hasValidation) {
    schema.dependentRequired?.forEach((key, deps) {
      if (map.containsKey(key)) {
        for (final dep in deps) {
          if (!map.containsKey(dep)) {
            context.addError(
              'Property "$dep" is required because "$key" is present',
              path.append(dep),
              keyword: 'dependentRequired',
              schema: schema,
              value: value,
            );
          }
        }
      }
    });
  }

  if (hasApplicator) {
    schema.dependentSchemas?.forEach((key, depSchema) {
      if (map.containsKey(key)) {
        final depTracker = validator.validate(value, depSchema, path, context);
        tracker.merge(depTracker);
      }
    });
  }

  return tracker;
}
