// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import 'package:jsontool/jsontool.dart';
import 'descriptors.dart';
import 'schema.dart';
import 'parser.dart';

/// Custom exception tracking the nested path of validation or parse failure.
final class JsonParseException implements FormatException {
  @override
  final String message;

  @override
  final Object? source;

  @override
  final int? offset;

  /// The JSON path segments leading to the failure.
  final List<String> path;

  /// Creates a [JsonParseException] with the failure path.
  JsonParseException(this.message, this.source, this.offset, this.path);

  @override
  String toString() {
    final pathStr = path.isEmpty ? '' : ' at \$.${path.join('.')}';
    return 'JsonParseException$pathStr: $message';
  }
}

/// Helper function to wrap parsing exceptions, adding the path segment.
FormatException wrapException(FormatException e, dynamic pathSegment) {
  final List<String> pathList;
  if (pathSegment is List) {
    pathList = List<String>.from(pathSegment);
  } else {
    pathList = [pathSegment as String];
  }
  if (e is JsonParseException) {
    return JsonParseException(e.message, e.source, e.offset, [
      ...pathList,
      ...e.path,
    ]);
  }
  return JsonParseException(e.message, e.source, e.offset, pathList);
}

/// Base interface for all models generated by json_schema_gen.
abstract interface class JsonModel implements JsonWritable {
  /// Validates the model instance against schema constraints.
  void validate();

  /// Converts the model to a JSON-compatible Dart value (Map, List, primitive, etc.).
  Object? toJsonValue();
}

/// Exception thrown when schema validation fails.
final class JsonValidationException implements Exception {
  /// The validation error message.
  final String message;

  /// The JSON path segments leading to the validation failure.
  final List<String> path;

  /// Creates a [JsonValidationException] with the validation failure path.
  JsonValidationException(this.message, [this.path = const []]);

  @override
  String toString() {
    final pathStr = path.isEmpty ? '' : ' at \$.${path.join('.')}';
    return 'JsonValidationException$pathStr: $message';
  }
}

/// Read any dynamic JSON value from [reader].
dynamic readAny(JsonReader reader) {
  dynamic result;
  final writer = jsonObjectWriter((value) {
    result = value;
  });
  reader.expectAnyValue(writer);
  return result;
}

/// Writes any arbitrary Dart JSON structure to [sink].
void writeAny(JsonSink sink, dynamic value) {
  if (value == null) {
    sink.addNull();
  } else if (value is bool) {
    sink.addBool(value);
  } else if (value is num) {
    sink.addNumber(value);
  } else if (value is String) {
    sink.addString(value);
  } else if (value is List) {
    sink.startArray();
    for (final item in value) {
      writeAny(sink, item);
    }
    sink.endArray();
  } else if (value is Map) {
    sink.startObject();
    value.forEach((key, val) {
      sink.addKey(key.toString());
      writeAny(sink, val);
    });
    sink.endObject();
  } else if (value is JsonWritable) {
    value.writeJson(sink);
  } else {
    throw ArgumentError(
      'Unsupported value type for serialization: ${value.runtimeType}',
    );
  }
}

/// Base class for execution frames used during non-recursive parsing.
sealed class JsonParseFrame {
  /// The result of parsing this frame.
  dynamic get result;

  /// The current path segment being parsed.
  String? get currentPathSegment;

  /// Resumes execution of this frame with a parsed child [value].
  void resume(dynamic value);

  /// Executes parsing logic for this frame.
  ///
  /// Returns `true` if the frame is complete.
  bool execute(JsonReader reader, List<JsonParseFrame> stack);
}

final class _ObjectFrame extends JsonParseFrame {
  final ObjectDescriptor desc;
  final bool validate;
  final Map<String, dynamic> fields = {};
  bool _initialized = false;
  String? _currentKey;
  dynamic _result;

  _ObjectFrame(this.desc, {this.validate = true});

  @override
  dynamic get result => _result;

  @override
  String? get currentPathSegment => _currentKey;

  @override
  void resume(dynamic value) {
    if (_currentKey != null) {
      fields[_currentKey!] = value;
      _currentKey = null;
    }
  }

  @override
  bool execute(JsonReader reader, List<JsonParseFrame> stack) {
    if (!_initialized) {
      reader.expectObject();
      _initialized = true;
    }
    if (reader.hasNextKey()) {
      final key = reader.nextKey()!;
      final prop = desc.properties[key];
      if (prop != null) {
        _currentKey = key;
        _pushSchemaFrame(reader, stack, prop.schema, (val) {
          fields[key] = val;
          _currentKey = null;
        }, validate: validate);
      } else {
        final matchingPatterns = desc.patternProperties.entries
            .where((e) => e.key.hasMatch(key))
            .toList();
        if (matchingPatterns.isNotEmpty) {
          _currentKey = key;
          _pushSchemaFrame(reader, stack, matchingPatterns.first.value, (val) {
            fields[key] = val;
            _currentKey = null;
          }, validate: validate);
        } else if (desc.additionalProperties != null) {
          _currentKey = key;
          _pushSchemaFrame(reader, stack, desc.additionalProperties!, (val) {
            fields[key] = val;
            _currentKey = null;
          }, validate: validate);
        } else {
          reader.skipAnyValue();
        }
      }
      return false;
    } else {
      for (final req in desc.required) {
        if (!fields.containsKey(req)) {
          throw reader.fail('Missing required property: $req');
        }
      }
      _result = desc.instantiate(fields);
      if (validate && _result is JsonModel) {
        (_result as JsonModel).validate();
      }
      stack.removeLast();
      if (stack.isNotEmpty) {
        stack.last.resume(_result);
      }
      return false;
    }
  }
}

/// Parse frame for array descriptors.
final class ArrayFrame<T> extends JsonParseFrame {
  /// The descriptor for this array.
  final ArrayDescriptor<T> desc;

  /// Whether to validate parsed items.
  final bool validate;

  /// The accumulated list of items.
  final List<T> list = [];

  /// Internal state tracking initialization.
  bool _initialized = false;

  /// Current index being parsed.
  int index = 0;
  dynamic _result;

  /// Creates an [ArrayFrame].
  ArrayFrame(this.desc, {this.validate = true});

  @override
  dynamic get result => list;

  @override
  String? get currentPathSegment => '[$index]';

  @override
  void resume(dynamic value) {
    list.add(value as T);
    index++;
  }

  @override
  bool execute(JsonReader reader, List<JsonParseFrame> stack) {
    if (!_initialized) {
      reader.expectArray();
      _initialized = true;
    }
    if (reader.hasNext()) {
      final itemDesc =
          (desc.prefixItems != null && index < desc.prefixItems!.length)
          ? desc.prefixItems![index]
          : desc.items;
      _pushSchemaFrame(reader, stack, itemDesc, (val) {
        list.add(val as T);
        index++;
      }, validate: validate);
      return false;
    } else {
      _result = list;
      stack.removeLast();
      if (stack.isNotEmpty) {
        stack.last.resume(_result);
      }
      return false;
    }
  }
}

final class _UnionFrame extends JsonParseFrame {
  final UnionDescriptor desc;
  final bool validate;
  dynamic _result;
  UnionOptionDescriptor? _pendingOption;

  _UnionFrame(this.desc, {this.validate = true});

  @override
  dynamic get result => _result;

  @override
  String? get currentPathSegment => null;

  @override
  void resume(dynamic value) {
    if (_pendingOption != null) {
      _result = _pendingOption!.wrap(value);
      _pendingOption = null;
    } else {
      _result = value;
    }
  }

  @override
  bool execute(JsonReader reader, List<JsonParseFrame> stack) {
    if (_result != null) {
      if (validate && _result is JsonModel) {
        (_result as JsonModel).validate();
      }
      stack.removeLast();
      if (stack.isNotEmpty) {
        stack.last.resume(_result);
      }
      return false;
    }

    if (desc.discriminatorProperty != null) {
      final rCopy = reader.copy();
      rCopy.expectObject();
      String? discValue;
      while (rCopy.hasNextKey()) {
        final key = rCopy.nextKey();
        if (key == desc.discriminatorProperty) {
          discValue = rCopy.expectString();
          break;
        } else {
          rCopy.skipAnyValue();
        }
      }
      if (discValue == null) {
        throw reader.fail(
          'Missing discriminator property: ${desc.discriminatorProperty}',
        );
      }
      final option = desc.discriminatorMapping?[discValue];
      if (option == null) {
        throw reader.fail('Unknown discriminator value: $discValue');
      }
      _pendingOption = option;
      _pushSchemaFrame(reader, stack, option.schema, (val) {
        _result = option.wrap(val);
        _pendingOption = null;
      }, validate: validate);
      return false;
    } else {
      FormatException? lastException;
      for (final option in desc.activeOptions) {
        final rCopy = reader.copy();
        try {
          _runNonRecursiveWithDescriptor(rCopy, option.schema, validate: false);
          _pendingOption = option;
          _pushSchemaFrame(reader, stack, option.schema, (val) {
            _result = option.wrap(val);
            _pendingOption = null;
          }, validate: validate);
          return false;
        } on FormatException catch (e) {
          lastException = e;
        }
      }
      throw reader.fail(
        'Failed to parse ${desc.title} union. Last error: ${lastException?.message}',
      );
    }
  }
}

final class _NotFrame extends JsonParseFrame {
  final NotDescriptor desc;
  final bool validate;
  dynamic _result;

  _NotFrame(this.desc, {this.validate = true});

  @override
  dynamic get result => _result;

  @override
  String? get currentPathSegment => null;

  @override
  void resume(dynamic value) {
    // Speculative parsing is done synchronously, so this should not be called.
  }

  @override
  bool execute(JsonReader reader, List<JsonParseFrame> stack) {
    if (validate) {
      final rCopy = reader.copy();
      bool matched = false;
      try {
        _runNonRecursiveWithDescriptor(rCopy, desc.inner, validate: validate);
        matched = true;
      } on JsonValidationException {
        // OK
      } on FormatException {
        // OK
      }

      if (matched) {
        throw JsonValidationException('Value must not match the schema');
      }
    }

    _result = readAny(reader);
    stack.removeLast();
    if (stack.isNotEmpty) {
      stack.last.resume(_result);
    }
    return false;
  }
}

void _pushSchemaFrame(
  JsonReader reader,
  List<JsonParseFrame> stack,
  SchemaDescriptor schema,
  void Function(dynamic value) onComplete, {
  required bool validate,
}) {
  if (schema is NullableDescriptor) {
    if (reader.checkNull()) {
      reader.expectNull();
      onComplete(null);
    } else {
      _pushSchemaFrame(
        reader,
        stack,
        schema.inner,
        onComplete,
        validate: validate,
      );
    }
  } else if (schema is PrimitiveDescriptor) {
    onComplete(schema.read(reader));
  } else if (schema is AnythingDescriptor) {
    onComplete(readAny(reader));
  } else if (schema is EnumDescriptor) {
    final val = schema.base.read(reader);
    try {
      onComplete(schema.fromValue(val));
    } catch (e) {
      throw reader.fail('Invalid enum value: $val');
    }
  } else if (schema is ObjectDescriptor) {
    stack.add(_ObjectFrame(schema, validate: validate));
  } else if (schema is ArrayDescriptor) {
    stack.add(schema.createFrame(validate: validate));
  } else if (schema is UnionDescriptor) {
    stack.add(_UnionFrame(schema, validate: validate));
  } else if (schema is NotDescriptor) {
    stack.add(_NotFrame(schema, validate: validate));
  } else if (schema is NeverDescriptor) {
    throw reader.fail('Value is not allowed here');
  }
}

dynamic _runNonRecursiveWithDescriptor(
  JsonReader reader,
  SchemaDescriptor rootSchema, {
  bool validate = true,
}) {
  if (rootSchema is NullableDescriptor) {
    if (reader.checkNull()) {
      reader.expectNull();
      return null;
    }
    return _runNonRecursiveWithDescriptor(
      reader,
      rootSchema.inner,
      validate: validate,
    );
  }
  if (rootSchema is PrimitiveDescriptor) {
    return rootSchema.read(reader);
  } else if (rootSchema is AnythingDescriptor) {
    return readAny(reader);
  } else if (rootSchema is EnumDescriptor) {
    final val = rootSchema.base.read(reader);
    try {
      return rootSchema.fromValue(val);
    } catch (e) {
      throw reader.fail('Invalid enum value: $val');
    }
  }

  final rootFrame = _createFrameForSchema(rootSchema, validate: validate);
  final stack = <JsonParseFrame>[rootFrame];
  try {
    while (stack.isNotEmpty) {
      final current = stack.last;
      final isComplete = current.execute(reader, stack);
      if (isComplete) {
        stack.removeLast();
      }
    }
    return rootFrame.result;
  } on JsonValidationException catch (e) {
    final path = <String>[];
    for (final frame in stack) {
      final segment = frame.currentPathSegment;
      if (segment != null) {
        path.add(segment);
      }
    }
    final propName = path.isNotEmpty ? path.last : null;
    final message = (propName != null && e.message.startsWith('Value '))
        ? e.message.replaceFirst('Value ', 'Property "$propName" ')
        : e.message;
    throw JsonValidationException(message, [...path, ...e.path]);
  } on FormatException catch (e) {
    final path = <String>[];
    for (final frame in stack) {
      final segment = frame.currentPathSegment;
      if (segment != null) {
        path.add(segment);
      }
    }
    throw wrapException(e, path);
  }
}

JsonParseFrame _createFrameForSchema(
  SchemaDescriptor schema, {
  required bool validate,
}) {
  if (schema is ObjectDescriptor) {
    return _ObjectFrame(schema, validate: validate);
  } else if (schema is ArrayDescriptor) {
    return schema.createFrame(validate: validate);
  } else if (schema is UnionDescriptor) {
    return _UnionFrame(schema, validate: validate);
  } else if (schema is NotDescriptor) {
    return _NotFrame(schema, validate: validate);
  }
  throw UnsupportedError('Primitive schemas do not require frame creation.');
}

/// Parses JSON from [reader] using the given [schema] descriptor.
///
/// If [validate] is true (default), it will validate the JSON against the
/// schema constraints during parsing.
///
/// Throws [JsonParseException] if the JSON is malformed or cannot be parsed.
/// Throws [JsonValidationException] if the JSON does not conform to the schema.
dynamic parseWithDescriptor(
  JsonReader reader,
  SchemaDescriptor schema, {
  bool validate = true,
}) {
  return _runNonRecursiveWithDescriptor(reader, schema, validate: validate);
}

/// Writes [value] to [sink] using the given [schema] descriptor.
///
/// The [value] must match the structure expected by the [schema] descriptor.
///
/// Throws [ArgumentError] if the value cannot be serialized.
void writeWithDescriptor<T>(
  JsonSink sink,
  T value,
  SchemaDescriptor<T> schema,
) {
  _writeSchemaValue(sink, value, schema);
}

void _writeSchemaValue(JsonSink sink, Object? value, SchemaDescriptor schema) {
  if (schema is NullableDescriptor) {
    if (value == null) {
      sink.addNull();
    } else {
      _writeSchemaValue(sink, value, schema.inner);
    }
    return;
  }
  if (schema is PrimitiveDescriptor) {
    schema.write(sink, value);
  } else if (schema is AnythingDescriptor) {
    writeAny(sink, value);
  } else if (schema is NotDescriptor) {
    writeAny(sink, value);
  } else if (schema is EnumDescriptor) {
    final backingVal = schema.toValue(value);
    schema.base.write(sink, backingVal);
  } else if (schema is ArrayDescriptor) {
    sink.startArray();
    if (value is List) {
      for (var i = 0; i < value.length; i++) {
        final item = value[i];
        final itemSchema =
            (schema.prefixItems != null && i < schema.prefixItems!.length)
            ? schema.prefixItems![i]
            : schema.items;
        _writeSchemaValue(sink, item, itemSchema);
      }
    }
    sink.endArray();
  } else if (schema is ObjectDescriptor) {
    sink.startObject();
    final fields = schema.getFields(value);
    schema.properties.forEach((key, prop) {
      final val = fields[key];
      if (val != null) {
        sink.addKey(key);
        _writeSchemaValue(sink, val, prop.schema);
      }
    });
    fields.forEach((key, val) {
      if (schema.properties.containsKey(key)) return;
      if (val == null) return;

      final matchingPatterns = schema.patternProperties.entries
          .where((e) => e.key.hasMatch(key))
          .toList();
      if (matchingPatterns.isNotEmpty) {
        sink.addKey(key);
        _writeSchemaValue(sink, val, matchingPatterns.first.value);
      } else if (schema.additionalProperties != null &&
          schema.additionalProperties is! NeverDescriptor) {
        sink.addKey(key);
        _writeSchemaValue(sink, val, schema.additionalProperties!);
      }
    });
    sink.endObject();
  } else if (schema is UnionDescriptor) {
    if (value is JsonWritable) {
      value.writeJson(sink);
    }
  }
}

/// Validates if a string is a valid hostname according to RFC 1034.
///
/// A hostname must be at most 253 characters long.
/// Labels must be separated by dots and be at most 63 characters long,
/// containing only alphanumeric characters and hyphens, and not starting
/// or ending with a hyphen.
bool isValidHostname(String s) {
  if (s.length > 253) return false;
  final labelRegex = RegExp(
    r'^([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])$',
  );
  final labels = s.split('.');
  for (final label in labels) {
    if (!labelRegex.hasMatch(label)) return false;
  }
  return true;
}

/// Validates if a string is a valid IPv6 address according to RFC 3986.
bool isValidIPv6(String s) {
  final ipv6Regex = RegExp(
    r'^((([0-9A-Fa-f]{1,4}:){7}[0-9A-Fa-f]{1,4})|'
    r'(([0-9A-Fa-f]{1,4}:){1,7}:)|'
    r'(([0-9A-Fa-f]{1,4}:){1,6}:[0-9A-Fa-f]{1,4})|'
    r'(([0-9A-Fa-f]{1,4}:){1,5}:([0-9A-Fa-f]{1,4}:){1,2}[0-9A-Fa-f]{1,4})|'
    r'(([0-9A-Fa-f]{1,4}:){1,4}:([0-9A-Fa-f]{1,4}:){1,3}[0-9A-Fa-f]{1,4})|'
    r'(([0-9A-Fa-f]{1,4}:){1,3}:([0-9A-Fa-f]{1,4}:){1,4}[0-9A-Fa-f]{1,4})|'
    r'(([0-9A-Fa-f]{1,4}:){1,2}:([0-9A-Fa-f]{1,4}:){1,5}[0-9A-Fa-f]{1,4})|'
    r'([0-9A-Fa-f]{1,4}::([0-9A-Fa-f]{1,4}:){1,6}[0-9A-Fa-f]{1,4})|'
    r'(:(:([0-9A-Fa-f]{1,4}:){0,7}[0-9A-Fa-f]{1,4}|:))|'
    r'(fe80:(:[0-9A-Fa-f]{1,4}){0,4}%[0-9a-zA-Z]{1,})|'
    r'(::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))|'
    r'(([0-9A-Fa-f]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])))$',
  );
  return ipv6Regex.hasMatch(s);
}

/// Validates if a string is a valid time string (HH:MM:SS.sss) according to RFC 3339.
bool isValidTime(String s) {
  final timeRegex = RegExp(
    r'^([01][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?([zZ]|[+-](?:[01][0-9]|2[0-3]):[0-5][0-9])$',
  );
  return timeRegex.hasMatch(s);
}

/// Validates if a string is a valid URI reference according to RFC 3986.
bool isValidUriReference(String s) {
  if (Uri.tryParse(s) == null) return false;
  final allowedChars = RegExp(r"^[A-Za-z0-9\-._~:/?#\[\]@!$&'()*+,;=%]*$");
  if (!allowedChars.hasMatch(s)) return false;

  final percentCheck = RegExp(r'%[0-9a-fA-F]{2}');
  var index = 0;
  while ((index = s.indexOf('%', index)) != -1) {
    if (index + 2 >= s.length) return false;
    final part = s.substring(index, index + 3);
    if (!percentCheck.hasMatch(part)) return false;
    index += 3;
  }
  return true;
}

/// Validates if a string is a valid absolute URI according to RFC 3986.
bool isValidUri(String s) {
  if (!isValidUriReference(s)) return false;
  final parsed = Uri.tryParse(s);
  return parsed != null && parsed.hasScheme;
}

/// Extension on [Schema] to support runtime validation.
extension SchemaValidationExtension on Schema {
  /// Validates [value] against this schema.
  ///
  /// Throws [JsonValidationException] if validation fails.
  void validate(dynamic value) {
    _validate(value, this, []);
  }
}

/// Creates a validator function for the given JSON [schema].
///
/// The returned function takes a decoded JSON value and validates it.
/// It throws [JsonValidationException] if validation fails.
void Function(dynamic) createValidator(Map<String, dynamic> schema) {
  final parser = SchemaParser(schema);
  final parsedSchema = parser.parse();
  return parsedSchema.validate;
}

void _validate(dynamic value, Schema schema, List<String> path) {
  // Check 'not' on the current schema level
  if (schema.not != null) {
    bool matches = true;
    try {
      _validate(value, schema.not!, path);
    } on JsonValidationException {
      matches = false;
    }
    if (matches) {
      throw JsonValidationException('Value must not match the schema', path);
    }
  }

  if (schema is RefSchema) {
    _validate(value, schema.realSchema, path);
    return;
  }

  switch (schema) {
    case AnythingSchema _:
      break;
    case NeverSchema _:
      throw JsonValidationException('Value matches "never" schema', path);
    case NullSchema _:
      if (value != null) {
        throw JsonValidationException('Value must be null', path);
      }
      break;
    case BooleanSchema _:
      if (value is! bool) {
        throw JsonValidationException('Value must be a boolean', path);
      }
      break;
    case NumberSchema s:
      _validateNumber(value, s, path);
      break;
    case StringSchema s:
      _validateString(value, s, path);
      break;
    case ArraySchema s:
      _validateArray(value, s, path);
      break;
    case ObjectSchema s:
      _validateObject(value, s, path);
      break;
    case EnumSchema s:
      _validateEnum(value, s, path);
      break;
    case UnionSchema s:
      _validateUnion(value, s, path);
      break;
    case AllOfSchema s:
      _validateAllOf(value, s, path);
      break;
    default:
      throw UnimplementedError(
        'Validation for ${schema.runtimeType} is not implemented',
      );
  }
}

void _validateNumber(dynamic value, NumberSchema schema, List<String> path) {
  if (schema.isInteger) {
    if (value is! int) {
      throw JsonValidationException('Value must be an integer', path);
    }
  } else {
    if (value is! num) {
      throw JsonValidationException('Value must be a number', path);
    }
  }

  final val = value as num;
  if (schema.minimum != null && val < schema.minimum!) {
    throw JsonValidationException('Value must be >= ${schema.minimum}', path);
  }
  if (schema.maximum != null && val > schema.maximum!) {
    throw JsonValidationException('Value must be <= ${schema.maximum}', path);
  }
  if (schema.exclusiveMinimum != null && val <= schema.exclusiveMinimum!) {
    throw JsonValidationException(
      'Value must be > ${schema.exclusiveMinimum}',
      path,
    );
  }
  if (schema.exclusiveMaximum != null && val >= schema.exclusiveMaximum!) {
    throw JsonValidationException(
      'Value must be < ${schema.exclusiveMaximum}',
      path,
    );
  }
  if (schema.multipleOf != null) {
    if (schema.isInteger) {
      if (val % schema.multipleOf! != 0) {
        throw JsonValidationException(
          'Value must be a multiple of ${schema.multipleOf}',
          path,
        );
      }
    } else {
      if ((val / schema.multipleOf! - (val / schema.multipleOf!).round())
              .abs() >
          1e-9) {
        throw JsonValidationException(
          'Value must be a multiple of ${schema.multipleOf}',
          path,
        );
      }
    }
  }
}

void _validateString(dynamic value, StringSchema schema, List<String> path) {
  if (value is! String) {
    throw JsonValidationException('Value must be a string', path);
  }
  if (schema.minLength != null && value.length < schema.minLength!) {
    throw JsonValidationException(
      'Value length must be >= ${schema.minLength}',
      path,
    );
  }
  if (schema.maxLength != null && value.length > schema.maxLength!) {
    throw JsonValidationException(
      'Value length must be <= ${schema.maxLength}',
      path,
    );
  }
  if (schema.pattern != null) {
    if (!RegExp(schema.pattern!).hasMatch(value)) {
      throw JsonValidationException(
        'Value must match pattern ${schema.pattern}',
        path,
      );
    }
  }
  if (schema.format != null) {
    _validateFormat(value, schema.format!, path);
  }
}

void _validateFormat(String value, String format, List<String> path) {
  switch (format) {
    case 'date-time':
      if (DateTime.tryParse(value) == null) {
        throw JsonValidationException(
          'Value must be a valid RFC 3339 date-time string',
          path,
        );
      }
      break;
    case 'date':
      if (!RegExp(r'^\d{4}-\d{2}-\d{2}$').hasMatch(value)) {
        throw JsonValidationException(
          'Value must be a valid date string (YYYY-MM-DD)',
          path,
        );
      }
      break;
    case 'email':
      if (!RegExp(r'^[^@]+@[^@]+$').hasMatch(value)) {
        throw JsonValidationException(
          'Value must be a valid email address',
          path,
        );
      }
      break;
    case 'ipv4':
      if (!RegExp(
        r'^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$',
      ).hasMatch(value)) {
        throw JsonValidationException(
          'Value must be a valid IPv4 address',
          path,
        );
      }
      break;
    case 'uuid':
      if (!RegExp(
        r'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
      ).hasMatch(value)) {
        throw JsonValidationException('Value must be a valid UUID', path);
      }
      break;
    case 'uri':
      if (!isValidUri(value)) {
        throw JsonValidationException(
          'Value must be a valid absolute URI',
          path,
        );
      }
      break;
    case 'uri-reference':
      if (!isValidUriReference(value)) {
        throw JsonValidationException(
          'Value must be a valid URI reference',
          path,
        );
      }
      break;
    case 'ipv6':
      if (!isValidIPv6(value)) {
        throw JsonValidationException(
          'Value must be a valid IPv6 address',
          path,
        );
      }
      break;
    case 'hostname':
      if (!isValidHostname(value)) {
        throw JsonValidationException('Value must be a valid hostname', path);
      }
      break;
    case 'time':
      if (!isValidTime(value)) {
        throw JsonValidationException(
          'Value must be a valid time string',
          path,
        );
      }
      break;
  }
}

void _validateArray(dynamic value, ArraySchema schema, List<String> path) {
  if (value is! List) {
    throw JsonValidationException('Value must be an array', path);
  }
  if (schema.minItems != null && value.length < schema.minItems!) {
    throw JsonValidationException(
      'Value must have >= ${schema.minItems} items',
      path,
    );
  }
  if (schema.maxItems != null && value.length > schema.maxItems!) {
    throw JsonValidationException(
      'Value must have <= ${schema.maxItems} items',
      path,
    );
  }
  if (schema.uniqueItems == true) {
    for (var i = 0; i < value.length; i++) {
      for (var j = i + 1; j < value.length; j++) {
        if (_deepEquals(value[i], value[j])) {
          throw JsonValidationException('Value items must be unique', path);
        }
      }
    }
  }

  final prefixLength = schema.prefixItems?.length ?? 0;
  if (schema.prefixItems != null) {
    for (var i = 0; i < schema.prefixItems!.length; i++) {
      if (i < value.length) {
        _validate(value[i], schema.prefixItems![i], [...path, '[$i]']);
      }
    }
  }

  for (var i = prefixLength; i < value.length; i++) {
    _validate(value[i], schema.items, [...path, '[$i]']);
  }

  if (schema.contains != null) {
    var containsCount = 0;
    for (var i = 0; i < value.length; i++) {
      try {
        _validate(value[i], schema.contains!, [...path, '[$i]']);
        containsCount++;
      } on JsonValidationException {
        // Ignore
      }
    }
    final minContains = schema.minContains ?? 1;
    if (containsCount < minContains) {
      throw JsonValidationException(
        'Value must contain at least $minContains items matching contains schema',
        path,
      );
    }
    if (schema.maxContains != null && containsCount > schema.maxContains!) {
      throw JsonValidationException(
        'Value must contain at most ${schema.maxContains} items matching contains schema',
        path,
      );
    }
  }
}

void _validateObject(dynamic value, ObjectSchema schema, List<String> path) {
  if (value is! Map) {
    throw JsonValidationException('Value must be an object', path);
  }
  final map = value;

  // Check required
  for (final req in schema.required) {
    if (!map.containsKey(req)) {
      throw JsonValidationException('Missing required property: $req', [
        ...path,
        req,
      ]);
    }
  }

  // Check min/max properties
  if (schema.minProperties != null && map.length < schema.minProperties!) {
    throw JsonValidationException(
      'Object must have >= ${schema.minProperties} properties',
      path,
    );
  }
  if (schema.maxProperties != null && map.length > schema.maxProperties!) {
    throw JsonValidationException(
      'Object must have <= ${schema.maxProperties} properties',
      path,
    );
  }

  // Validate properties
  map.forEach((key, val) {
    if (key is! String) {
      throw JsonValidationException('Object keys must be strings', path);
    }
    final propSchema = schema.properties[key];
    if (propSchema != null) {
      _validate(val, propSchema, [...path, key]);
    }

    var matchedPattern = false;
    schema.patternProperties.forEach((pattern, patternSchema) {
      if (pattern.hasMatch(key)) {
        matchedPattern = true;
        _validate(val, patternSchema, [...path, key]);
      }
    });

    if (propSchema == null && !matchedPattern) {
      // Additional properties
      final addProps = schema.additionalProperties;
      if (addProps != null) {
        _validate(val, addProps, [...path, key]);
      }
    }
  });

  // Check dependentRequired
  schema.dependentRequired.forEach((key, deps) {
    if (map.containsKey(key)) {
      for (final dep in deps) {
        if (!map.containsKey(dep)) {
          throw JsonValidationException(
            'Property "$dep" is required because "$key" is present',
            [...path, dep],
          );
        }
      }
    }
  });
}

void _validateEnum(dynamic value, EnumSchema schema, List<String> path) {
  _validate(value, schema.baseSchema, path);
  final contains = schema.values.any((v) => _deepEquals(v, value));
  if (!contains) {
    throw JsonValidationException(
      'Value must be one of ${schema.values}',
      path,
    );
  }
}

void _validateUnion(dynamic value, UnionSchema schema, List<String> path) {
  if (schema.discriminator != null) {
    final disc = schema.discriminator!;
    if (value is! Map || !value.containsKey(disc.propertyName)) {
      throw JsonValidationException(
        'Missing discriminator property: ${disc.propertyName}',
        path,
      );
    }
    final discValue = value[disc.propertyName];
    if (discValue is! String) {
      throw JsonValidationException('Discriminator property must be a string', [
        ...path,
        disc.propertyName,
      ]);
    }

    final matchedSchema = _findMatchingSchema(
      discValue,
      schema.subschemas,
      disc.mapping,
    );
    if (matchedSchema != null) {
      _validate(value, matchedSchema, path);
      return;
    } else {
      throw JsonValidationException(
        'Could not find matching schema for discriminator value "$discValue"',
        path,
      );
    }
  }

  var matchCount = 0;
  final errors = <JsonValidationException>[];
  for (final sub in schema.subschemas) {
    try {
      _validate(value, sub, path);
      matchCount++;
      break; // anyOf, first match is enough for runtime validation
    } on JsonValidationException catch (e) {
      errors.add(e);
    }
  }

  if (matchCount == 0) {
    throw JsonValidationException(
      'Value does not match any of the union schemas. Errors: ${errors.map((e) => e.message).join(', ')}',
      path,
    );
  }
}

Schema? _findMatchingSchema(
  String discValue,
  List<Schema> subschemas,
  Map<String, String>? mapping,
) {
  if (mapping != null) {
    final targetRef = mapping[discValue];
    if (targetRef != null) {
      for (final sub in subschemas) {
        if (sub is RefSchema && sub.ref == targetRef) {
          return sub;
        }
      }
    }
  }

  for (final sub in subschemas) {
    final real = sub.realSchema;
    if (real.title == discValue) {
      return sub;
    }
    if (sub is RefSchema) {
      final lastSegment = sub.ref.split('/').last;
      if (lastSegment == discValue) {
        return sub;
      }
    }
  }
  return null;
}

void _validateAllOf(dynamic value, AllOfSchema schema, List<String> path) {
  for (final sub in schema.subschemas) {
    _validate(value, sub, path);
  }
}

bool _deepEquals(dynamic a, dynamic b) {
  if (identical(a, b)) return true;
  if (a is List && b is List) {
    if (a.length != b.length) return false;
    for (var i = 0; i < a.length; i++) {
      if (!_deepEquals(a[i], b[i])) return false;
    }
    return true;
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) return false;
    for (final key in a.keys) {
      if (!b.containsKey(key)) return false;
      if (!_deepEquals(a[key], b[key])) return false;
    }
    return true;
  }
  return a == b;
}
